/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Open to every approved user. Returns the same projection
         *     everyone else sees — names + email + chapter memberships.
         *     No "see only your own row" mode; the visibility matches the
         *     organising context the project is built for.
         */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/pending-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending User Count
         * @description How many live users are awaiting admin approval. Backs the
         *     red-dot indicator on the navbar's Accounts link — only
         *     rendered for admins, and the endpoint is admin-only too so
         *     organisers can't sniff the count.
         *
         *     Defined *before* ``GET /users`` so the static path beats
         *     FastAPI's parametric ``/users/{user_id}/...`` patterns; the
         *     explicit string segment wouldn't actually conflict with the
         *     list endpoint, but keeping all the static-segment routes up
         *     top is the cheapest way to never trip over that ordering rule
         *     in the future.
         */
        get: operations["pending_user_count_api_v1_admin_users_pending_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Soft-delete a user. Stamps ``deleted_at``; the email slot
         *     frees up via the partial-unique index, so registering again
         *     with the same address restores the row in an unapproved
         *     state.
         *
         *     Self-deletion is implicitly blocked because the permission
         *     matrix's DELETE_USER branch is admin-only and contains no
         *     self-service carve-out — an admin trying to delete their
         *     own row therefore goes through the matrix and is rejected
         *     by the explicit "not self" check we still keep here as
         *     defence in depth (and to give a clearer 409 over the
         *     matrix's blanket 403).
         */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve User
         * @description Mark a pending user approved and replace their membership
         *     set with ``chapter_ids``. The approval email lists every
         *     assigned chapter so the user knows the full scope of what
         *     they've been let into.
         */
        post: operations["approve_user_api_v1_admin_users__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/demote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demote User
         * @description Demote an admin back to organiser. The matrix blocks
         *     self-demotion — the same anti-foot-shoot rule that previously
         *     lived inline in this handler.
         */
        post: operations["demote_user_api_v1_admin_users__user_id__demote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote User */
        post: operations["promote_user_api_v1_admin_users__user_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename User
         * @description Update a user's display name. Self-service. The user-
         *     supplied value is stripped of surrounding whitespace; an
         *     empty-after-strip name is rejected before the row is touched
         *     (Pydantic's ``min_length`` doesn't strip).
         */
        post: operations["rename_user_api_v1_admin_users__user_id__rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/set-chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set User Chapters
         * @description Replace the user's full chapter membership set. Self-service:
         *     a user can manage their own chapter memberships without
         *     admin intervention. ``min_length=1`` on the schema keeps
         *     every approved user in at least one chapter — emptying the
         *     set would orphan you from the project.
         */
        post: operations["set_user_chapters_api_v1_admin_users__user_id__set_chapters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/complete-registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Registration
         * @description Redeem a registration token + supply the user's name. Creates
         *     (or restores) the user and returns a JWT — completing
         *     registration is the user's first sign-in.
         *
         *     Single-use: the token row is deleted on every terminal outcome
         *     (success, expired, race) so a clicked link can't be replayed
         *     and orphan rows don't accumulate.
         */
        post: operations["complete_registration_api_v1_auth_complete_registration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Redeem a login token. Single-use: the row is deleted on
         *     successful redemption so a forwarded link can't be replayed.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Link
         * @description Send a magic link.
         *
         *     Branches on whether the email matches a live user. Both
         *     branches return the same ``LinkSent`` so the API can't be
         *     probed for account existence.
         */
        post: operations["login_link_api_v1_auth_login_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chapters
         * @description List chapters. By default only active ones; pass
         *     ``include_archived=true`` to also surface soft-deleted ones (used
         *     by the admin autocomplete to support restore).
         */
        get: operations["list_chapters_api_v1_chapters_get"];
        put?: never;
        /** Create Chapter */
        post: operations["create_chapter_api_v1_chapters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive Chapter */
        delete: operations["archive_chapter_api_v1_chapters__chapter_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Chapter
         * @description Partial update — name and/or city. The city tuple is set
         *     together (display name + lat + lon); leaving all three at
         *     ``None`` in the payload clears a previously-set city. Pass
         *     nothing for ``city*`` keys to leave the current city
         *     untouched.
         */
        patch: operations["patch_chapter_api_v1_chapters__chapter_id__patch"];
        trace?: never;
    };
    "/api/v1/chapters/{chapter_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Chapter */
        post: operations["restore_chapter_api_v1_chapters__chapter_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{chapter_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chapter Usage
         * @description How many live users + events are currently linked to this
         *     chapter. The frontend calls this before opening the delete
         *     dialog so it can offer reassignment dropdowns when there's
         *     something at stake.
         */
        get: operations["chapter_usage_api_v1_chapters__chapter_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Archived Events */
        get: operations["list_archived_events_api_v1_events_archived_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Slug
         * @description Public event lookup. The response is identical for every
         *     visitor in the seconds between two organiser edits, so it's a
         *     perfect candidate for HTTP caching: a 60 s shared cache window
         *     (Coolify/Traefik / any CDN that fronts the app) keeps the
         *     common case off the DB entirely, and ``stale-while-revalidate``
         *     means a request after the 60 s expiry serves the still-warm
         *     payload while a single background fetch refreshes it.
         *
         *     The 60 s freshness window is the trade-off: an organiser edit
         *     is visible to *new* visitors after up to 60 s. Acceptable —
         *     edits during an active sign-up window are rare, and
         *     ``no-store`` would defeat the point of caching the highest-
         *     traffic public endpoint.
         */
        get: operations["get_event_by_slug_api_v1_events_by_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/email-preview/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Email Preview
         * @description Render the exact email that the dispatcher will send to a
         *     signup on this event.
         */
        get: operations["email_preview_api_v1_events_by_slug__slug__email_preview__channel__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/event.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Ics
         * @description Public RFC 5545 calendar download for one event. Universal —
         *     Google, Apple, Outlook, Proton, Thunderbird, every mobile
         *     calendar app imports it. UID is the event's stable ``id``,
         *     so re-importing after an organiser edit updates the existing
         *     entry instead of creating a duplicate.
         */
        get: operations["get_event_ics_api_v1_events_by_slug__slug__event_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/feedback-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback Form Preview
         * @description Preview of the post-event feedback form.
         */
        get: operations["feedback_form_preview_api_v1_events_by_slug__slug__feedback_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Qr */
        get: operations["get_event_qr_api_v1_events_by_slug__slug__qr_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Signup */
        post: operations["create_signup_api_v1_events_by_slug__slug__signups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Event */
        put: operations["update_event_api_v1_events__event_id__put"];
        post?: never;
        /**
         * Delete Event
         * @description Hard-delete an archived event. Refuses if the event isn't
         *     archived first — accidentally hard-deleting a live event
         *     with sign-ups would be a data-loss footgun. Cascades through
         *     ``signups`` / ``email_dispatches`` / ``feedback_responses`` /
         *     ``feedback_tokens`` via the FK ``ON DELETE CASCADE``s in the
         *     schema; the row + its dependents go with one DELETE.
         */
        delete: operations["delete_event_api_v1_events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Event */
        post: operations["archive_event_api_v1_events__event_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/feedback-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback Submissions
         * @description Per-submission feedback rows. One entry per ``submission_id``,
         *     keyed by question ``key`` (so a CSV consumer can index by
         *     question without joining to a questions table — there is no
         *     questions table; the keys are app-level constants). Used by
         *     the organiser-side CSV export.
         *
         *     Privacy: the ``submission_id`` is a random per-submission token
         *     with no link back to the signup that produced it — this matches
         *     the contract documented in the public privacy notice.
         */
        get: operations["feedback_submissions_api_v1_events__event_id__feedback_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/feedback-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Summary */
        get: operations["feedback_summary_api_v1_events__event_id__feedback_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Event */
        post: operations["restore_event_api_v1_events__event_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/send-emails/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Emails Now
         * @description Manually trigger the worker for one channel on a single
         *     event. Re-use of the generic dispatcher means the reminder
         *     + feedback "send now" buttons share one endpoint and one
         *     rate-limit budget.
         */
        post: operations["send_emails_now_api_v1_events__event_id__send_emails__channel__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Signups
         * @description Per-signup list for the organiser details page. Returns
         *     display_name + party_size + help_choices — never email,
         *     source, or feedback-email status.
         */
        get: operations["event_signups_api_v1_events__event_id__signups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/signups/{signup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Signup
         * @description Organiser-only hard-delete of a single signup row. Targets
         *     the case where someone (often the organiser themselves) wants
         *     a stray sign-up gone — accidental submission, duplicate row,
         *     test data left in a real event.
         *
         *     Privacy invariant unaffected: ``Signup`` carries no email, so
         *     deleting the row removes only headcount + display-name. Any
         *     pending ``EmailDispatch`` rows for this event live on by
         *     design (no signup_id link); the worker may still send a
         *     reminder/feedback email to the address the deleted signup
         *     submitted. That decoupling is the whole point — see
         *     ``models/email_dispatch.py``.
         */
        delete: operations["delete_signup_api_v1_events__event_id__signups__signup_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Stats Endpoint */
        get: operations["event_stats_endpoint_api_v1_events__event_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description The fixed-set questionnaire, used by the organiser-side preview page.
         */
        get: operations["list_questions_api_v1_feedback_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback Form */
        get: operations["get_feedback_form_api_v1_feedback__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{token}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_v1_feedback__token__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Cheap liveness — Coolify pings this every 30 s. A 2xx
         *     response is the only contract; deeper introspection lives on
         *     ``/health/full``.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Full
         * @description Liveness + ops introspection.
         *
         *     Beyond ``status: ok``, the response surfaces:
         *     * email-executor bounded worker count — a deploy that
         *       accidentally lifted the cap is visible at a glance;
         *     * Alembic schema head — the migration revision the running
         *       process believes the DB is at, so a Coolify deploy that
         *       forgot to run migrations is one curl away from being
         *       caught;
         *     * DB connectivity — a trivial ``SELECT 1`` round-trip;
         *     * oldest pending dispatch — surfaces a stuck queue (worker
         *       crashed, SMTP outage, etc.) before it shows up in user
         *       complaints.
         */
        get: operations["health_full_health_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApproveUserRequest
         * @description Approve a pending user, optionally also assigning them to
         *     chapters. The list may be empty — a freshly approved user
         *     with no chapters lands on the dashboard's onboarding banner
         *     where they self-pick. The admin doesn't have to know which
         *     chapters apply at approval time, which matters when the
         *     person who registered is the one with that context.
         */
        ApproveUserRequest: {
            /** Chapter Ids */
            chapter_ids?: string[];
        };
        /** AuthResponse */
        AuthResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * ChapterArchiveRequest
         * @description Optional reassignment targets when archiving a chapter.
         *     Both default to None — rows that aren't reassigned simply
         *     stay linked to the soft-deleted chapter (events become
         *     invisible until restore, users still have a chapter_id
         *     pointing at the archived chapter).
         */
        ChapterArchiveRequest: {
            /** Reassign Events To */
            reassign_events_to?: string | null;
            /** Reassign Users To */
            reassign_users_to?: string | null;
        };
        /** ChapterCreate */
        ChapterCreate: {
            /** Name */
            name: string;
        };
        /**
         * ChapterOut
         * @description One chapter, live or archived. ``archived`` mirrors
         *     ``deleted_at IS NOT NULL`` so the frontend doesn't need to
         *     inspect timestamps.
         */
        ChapterOut: {
            /** Archived */
            archived: boolean;
            /** City */
            city: string | null;
            /** City Lat */
            city_lat: number | null;
            /** City Lon */
            city_lon: number | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ChapterPatch
         * @description Partial update for a chapter. Either field may be omitted;
         *     the city tuple is all-or-nothing — passing ``city`` requires
         *     ``city_lat``/``city_lon`` (and vice versa) so we never end up
         *     with a city display name that has no coordinates.
         */
        ChapterPatch: {
            /** City */
            city?: string | null;
            /** City Lat */
            city_lat?: number | null;
            /** City Lon */
            city_lon?: number | null;
            /** Name */
            name?: string | null;
        };
        /**
         * ChapterRef
         * @description Lightweight chapter reference embedded in ``UserOut``. Just
         *     enough for the frontend to render a chip without a second
         *     round-trip.
         */
        ChapterRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ChapterUsageOut
         * @description How many users / events are currently assigned to this
         *     chapter. Used by the delete dialog so the admin sees what
         *     happens to dependents before confirming.
         */
        ChapterUsageOut: {
            /** Events */
            events: number;
            /** Users */
            users: number;
        };
        /**
         * CompleteRegistrationRequest
         * @description Redeems a registration token minted for an unknown email,
         *     supplying the only field we still need to create the user
         *     (their name). Returns an ``AuthResponse`` — completing
         *     registration is also the user's first sign-in.
         */
        CompleteRegistrationRequest: {
            /** Name */
            name: string;
            /** Token */
            token: string;
        };
        /**
         * EmailHealthOut
         * @description Aggregate of one channel's email delivery status across an
         *     event's signups. Counts always sum to ``signup_count``.
         */
        EmailHealthOut: {
            /** Failed */
            failed: number;
            /** Not Applicable */
            not_applicable: number;
            /** Pending */
            pending: number;
            /** Sent */
            sent: number;
        };
        /** EventCreate */
        EventCreate: {
            /** Chapter Id */
            chapter_id: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Feedback Enabled
             * @default true
             */
            feedback_enabled: boolean;
            /** Help Options */
            help_options?: string[];
            /** Latitude */
            latitude?: number | null;
            /**
             * Locale
             * @default nl
             * @enum {string}
             */
            locale: "nl" | "en";
            /** Location */
            location: string;
            /** Longitude */
            longitude?: number | null;
            /** Name */
            name: string;
            /**
             * Reminder Enabled
             * @default true
             */
            reminder_enabled: boolean;
            /** Source Options */
            source_options: string[];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Topic */
            topic?: string | null;
        };
        /** EventOut */
        EventOut: {
            /** Archived */
            archived: boolean;
            /** Attendee Count */
            attendee_count: number;
            /** Chapter Id */
            chapter_id: string | null;
            /** Chapter Name */
            chapter_name: string | null;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Feedback Enabled */
            feedback_enabled: boolean;
            /** Help Options */
            help_options: string[];
            /** Id */
            id: string;
            /** Latitude */
            latitude: number | null;
            /**
             * Locale
             * @enum {string}
             */
            locale: "nl" | "en";
            /** Location */
            location: string;
            /** Longitude */
            longitude: number | null;
            /** Name */
            name: string;
            /** Reminder Enabled */
            reminder_enabled: boolean;
            /** Slug */
            slug: string;
            /** Source Options */
            source_options: string[];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Topic */
            topic: string | null;
        };
        /**
         * EventStatsOut
         * @description Organiser-only aggregate. Never includes individual signups.
         */
        EventStatsOut: {
            /** By Help */
            by_help: {
                [key: string]: number;
            };
            /** By Source */
            by_source: {
                [key: string]: number;
            };
            /** Total Attendees */
            total_attendees: number;
            /** Total Signups */
            total_signups: number;
        };
        /** FeedbackAnswerIn */
        FeedbackAnswerIn: {
            /** Answer Int */
            answer_int?: number | null;
            /** Answer Text */
            answer_text?: string | null;
            /** Question Key */
            question_key: string;
        };
        /**
         * FeedbackFormOut
         * @description Public payload for GET /feedback/{token} — what the questionnaire
         *     page renders. Includes minimal event context so the page can show
         *     the user which event they're giving feedback on.
         */
        FeedbackFormOut: {
            /**
             * Event Locale
             * @enum {string}
             */
            event_locale: "nl" | "en";
            /** Event Name */
            event_name: string;
            /** Event Slug */
            event_slug: string;
            /** Questions */
            questions: components["schemas"]["FeedbackQuestionOut"][];
        };
        /**
         * FeedbackQuestionOut
         * @description Question shape for the public form. The frontend resolves the
         *     prompt + labels from i18n using ``key``. ``key`` is also the
         *     stable identifier the submit endpoint expects in answers.
         */
        FeedbackQuestionOut: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Ordinal */
            ordinal: number;
            /** Required */
            required: boolean;
        };
        /**
         * FeedbackQuestionSummary
         * @description Per-question aggregate. ``rating_distribution`` is a 1..5 array
         *     when kind=='rating' (counts at each scale point), or null. ``texts``
         *     is the list of free-text answers when kind=='text', or null.
         */
        FeedbackQuestionSummary: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Rating Average */
            rating_average?: number | null;
            /** Rating Distribution */
            rating_distribution?: number[] | null;
            /** Response Count */
            response_count: number;
            /** Texts */
            texts?: string[] | null;
        };
        /**
         * FeedbackSubmissionOut
         * @description One submission as a flat record — keyed by ``question.key`` so
         *     a CSV consumer can map columns by question identifier without
         *     needing the questions table. Rating values surface as the int;
         *     text answers as the string. Missing answers are absent from
         *     ``answers``. ``submission_id`` is the random per-submission id
         *     that has no link back to a signup (privacy contract).
         */
        FeedbackSubmissionOut: {
            /** Answers */
            answers: {
                [key: string]: number | string;
            };
            /** Submission Id */
            submission_id: string;
        };
        /** FeedbackSubmitIn */
        FeedbackSubmitIn: {
            /** Answers */
            answers: components["schemas"]["FeedbackAnswerIn"][];
        };
        /**
         * FeedbackSummaryOut
         * @description Organiser-only feedback summary for an event. ``email_health``
         *     is keyed by channel name (``reminder`` / ``feedback``) so the
         *     dashboard can surface delivery health for each side-by-side.
         */
        FeedbackSummaryOut: {
            /** Email Health */
            email_health: {
                [key: string]: components["schemas"]["EmailHealthOut"];
            };
            /** Questions */
            questions: components["schemas"]["FeedbackQuestionSummary"][];
            /** Response Rate */
            response_rate: number;
            /** Signup Count */
            signup_count: number;
            /** Submission Count */
            submission_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinkSent
         * @description Boring 200 response so /login-link can't be probed for whether
         *     an email is registered.
         */
        LinkSent: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * LoginLinkRequest
         * @description Single entry point for both populations: a registered email
         *     receives a sign-in link, an unknown email receives a
         *     "finish creating your account" link. The endpoint returns the
         *     same response shape either way so the API can't be probed for
         *     account existence.
         */
        LoginLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * LoginRequest
         * @description Redeems a magic-link token minted by /auth/login-link for an
         *     existing user. Single-use; the row is deleted on redemption.
         */
        LoginRequest: {
            /** Token */
            token: string;
        };
        /**
         * PendingCountOut
         * @description Tiny DTO for the navbar's pending-approval indicator. Admin-
         *     only — surfacing this to organisers would just be noise.
         */
        PendingCountOut: {
            /** Count */
            count: number;
        };
        /**
         * RenameUserRequest
         * @description Min-length=1 catches empty strings; the handler additionally
         *     strips whitespace and 422s on a name that's whitespace-only,
         *     since Pydantic's ``min_length`` doesn't strip.
         */
        RenameUserRequest: {
            /** Name */
            name: string;
        };
        /**
         * SetUserChaptersRequest
         * @description Replace the user's full chapter membership set. ``min_length=1``
         *     keeps approved users in at least one chapter — emptying the set
         *     is the same as de-activating them, which is what the delete
         *     endpoint is for.
         */
        SetUserChaptersRequest: {
            /** Chapter Ids */
            chapter_ids: string[];
        };
        /**
         * SignupAck
         * @description Public response after a successful signup. Returns nothing
         *     identifying — just confirms the booking landed.
         */
        SignupAck: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** SignupCreate */
        SignupCreate: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Help Choices */
            help_choices?: string[];
            /** Party Size */
            party_size: number;
            /** Source Choice */
            source_choice?: string | null;
        };
        /**
         * SignupSummaryOut
         * @description A single signup as seen on the organiser's details page.
         *     Deliberately minimal — name, headcount, help-choices. Never
         *     email, source, or feedback-email status; those exist on the
         *     model but are private to the worker. ``id`` is exposed so the
         *     organiser can target an individual row for deletion (e.g.
         *     cleaning up an accidental sign-up they made themselves).
         */
        SignupSummaryOut: {
            /** Display Name */
            display_name: string | null;
            /** Help Choices */
            help_choices: string[];
            /** Id */
            id: string;
            /** Party Size */
            party_size: number;
        };
        /** UserOut */
        UserOut: {
            /** Chapters */
            chapters: components["schemas"]["ChapterRef"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Is Approved */
            is_approved: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                pending?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_user_count_api_v1_admin_users_pending_count_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_user_api_v1_admin_users__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demote_user_api_v1_admin_users__user_id__demote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_user_api_v1_admin_users__user_id__promote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_user_api_v1_admin_users__user_id__rename_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_chapters_api_v1_admin_users__user_id__set_chapters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUserChaptersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_registration_api_v1_auth_complete_registration_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_link_api_v1_auth_login_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkSent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_api_v1_chapters_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chapter_api_v1_chapters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_chapter_api_v1_chapters__chapter_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ChapterArchiveRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_chapter_api_v1_chapters__chapter_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_chapter_api_v1_chapters__chapter_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chapter_usage_api_v1_chapters__chapter_id__usage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterUsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                chapter_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_archived_events_api_v1_events_archived_get: {
        parameters: {
            query?: {
                chapter_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_slug_api_v1_events_by_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_preview_api_v1_events_by_slug__slug__email_preview__channel__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_ics_api_v1_events_by_slug__slug__event_ics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_form_preview_api_v1_events_by_slug__slug__feedback_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackFormOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_qr_api_v1_events_by_slug__slug__qr_svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_signup_api_v1_events_by_slug__slug__signups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_v1_events__event_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_v1_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_event_api_v1_events__event_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_submissions_api_v1_events__event_id__feedback_submissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSubmissionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_summary_api_v1_events__event_id__feedback_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_event_api_v1_events__event_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_emails_now_api_v1_events__event_id__send_emails__channel__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_signups_api_v1_events__event_id__signups_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_signup_api_v1_events__event_id__signups__signup_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
                signup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stats_endpoint_api_v1_events__event_id__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_feedback_questions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_form_api_v1_feedback__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackFormOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback__token__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_full_health_full_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
