/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Soft-delete a user. Closes the SCD2 chain (``valid_until`` set,
         *     no replacement). The user can no longer log in — their email frees
         *     up the partial-unique slot, so registering again with the same
         *     address restores the chain in an unapproved state.
         *
         *     Self-deletion is blocked so the org can't lock itself out via a
         *     single click.
         */
        delete: operations["delete_user_api_v1_admin_users__entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{entity_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve User */
        post: operations["approve_user_api_v1_admin_users__entity_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{entity_id}/assign-chapter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Chapter
         * @description Move a user to a different chapter. Approved users always have
         *     one; setting NULL is not supported through this endpoint.
         */
        post: operations["assign_chapter_api_v1_admin_users__entity_id__assign_chapter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{entity_id}/demote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demote User
         * @description Demote an admin back to organiser. Self-demotion is blocked so
         *     the org can never end up with zero admins via a single click.
         */
        post: operations["demote_user_api_v1_admin_users__entity_id__demote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{entity_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote User */
        post: operations["promote_user_api_v1_admin_users__entity_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Redeem a magic-link token. Single-use: the row is deleted on
         *     successful redemption so a forwarded link can't be replayed.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Link
         * @description Send a magic-link email if the address is registered. Always
         *     returns 200 — never reveal whether the email exists.
         */
        post: operations["login_link_api_v1_auth_login_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create the account (or restore a previously-archived one) and
         *     send a magic link. The user becomes "real" only when they click
         *     the link — registration without redemption leaves an unapproved
         *     row that an admin still has to gate.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chapters
         * @description List chapters. By default only active ones; pass
         *     ``include_archived=true`` to also surface soft-deleted ones (used
         *     by the admin autocomplete to support restore).
         */
        get: operations["list_chapters_api_v1_chapters_get"];
        put?: never;
        /** Create Chapter */
        post: operations["create_chapter_api_v1_chapters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive Chapter */
        delete: operations["archive_chapter_api_v1_chapters__entity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Chapter
         * @description Partial SCD2 update for the chapter — name and/or city. The
         *     city tuple is set together (display name + lat + lon); leaving
         *     all three at ``None`` in the payload clears a previously-set
         *     city. Pass nothing for ``city*`` keys to leave the current city
         *     untouched.
         */
        patch: operations["patch_chapter_api_v1_chapters__entity_id__patch"];
        trace?: never;
    };
    "/api/v1/chapters/{entity_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Chapter */
        post: operations["restore_chapter_api_v1_chapters__entity_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{entity_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chapter Usage
         * @description How many users + events are currently linked to this chapter.
         *     The frontend calls this before opening the delete dialog so it
         *     can offer reassignment dropdowns when there's something at stake.
         */
        get: operations["chapter_usage_api_v1_chapters__entity_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Archived Events */
        get: operations["list_archived_events_api_v1_events_archived_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event By Slug */
        get: operations["get_event_by_slug_api_v1_events_by_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/email-preview/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Email Preview
         * @description Render the exact email that the dispatcher will send to a
         *     signup on this event. Public, no auth — links from the
         *     privacy explainer use it to show the visitor what they're
         *     consenting to before leaving an email address.
         *
         *     The feedback preview synthesises a placeholder ``?t=preview``
         *     URL since real per-signup tokens are minted only at send
         *     time.
         */
        get: operations["email_preview_api_v1_events_by_slug__slug__email_preview__channel__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/event.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Ics
         * @description Public RFC 5545 calendar download for one event. Universal —
         *     Google, Apple, Outlook, Proton, Thunderbird, every mobile
         *     calendar app imports it. UID is the event's stable
         *     ``entity_id``, so re-importing after an organiser edit updates
         *     the existing entry instead of creating a duplicate.
         */
        get: operations["get_event_ics_api_v1_events_by_slug__slug__event_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/feedback-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback Form Preview
         * @description Preview of the post-event feedback form.
         *
         *     The CTA in the feedback email's preview points here so an
         *     organiser can see exactly what attendees will fill in. No
         *     real ``FeedbackToken`` is involved — the SPA flags this
         *     response as a preview and disables the submit button.
         */
        get: operations["feedback_form_preview_api_v1_events_by_slug__slug__feedback_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Qr */
        get: operations["get_event_qr_api_v1_events_by_slug__slug__qr_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/by-slug/{slug}/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Signup */
        post: operations["create_signup_api_v1_events_by_slug__slug__signups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Event */
        put: operations["update_event_api_v1_events__entity_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Event */
        post: operations["archive_event_api_v1_events__entity_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/feedback-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback Submissions
         * @description Per-submission feedback rows. One entry per ``submission_id``,
         *     keyed by question ``key`` (so a CSV consumer can index by
         *     question without joining to the questions table). Used by the
         *     organiser-side CSV export.
         *
         *     Privacy: the ``submission_id`` is a random per-submission token
         *     with no link back to the signup that produced it — this matches
         *     the contract documented in the public privacy notice.
         */
        get: operations["feedback_submissions_api_v1_events__entity_id__feedback_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/feedback-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Summary */
        get: operations["feedback_summary_api_v1_events__entity_id__feedback_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Event */
        post: operations["restore_event_api_v1_events__entity_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/send-emails/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Emails Now
         * @description Manually trigger the worker for one channel on a single
         *     event. Re-use of the generic dispatcher means the reminder
         *     + feedback "send now" buttons share one endpoint and one
         *     rate-limit budget.
         */
        post: operations["send_emails_now_api_v1_events__entity_id__send_emails__channel__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Signups
         * @description Per-signup list for the organiser details page. Returns
         *     display_name + party_size + help_choices — never email,
         *     source, or feedback-email status. Ordered by signup time
         *     (oldest first) so a list rendered next to running totals
         *     stays stable as new signups arrive at the bottom.
         */
        get: operations["event_signups_api_v1_events__entity_id__signups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{entity_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Stats */
        get: operations["event_stats_api_v1_events__entity_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description The fixed-set questionnaire, used by the organiser-side preview page.
         */
        get: operations["list_questions_api_v1_feedback_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback Form */
        get: operations["get_feedback_form_api_v1_feedback__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{token}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_v1_feedback__token__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/scaleway-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scaleway Email Event */
        post: operations["scaleway_email_event_api_v1_webhooks_scaleway_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe + introspection for ops.
         *
         *     Beyond ``status: ok``, the response surfaces:
         *     * email-executor bounded worker count — a deploy that
         *       accidentally lifted the cap is visible at a glance;
         *     * Alembic schema head — the migration revision the running
         *       process believes the DB is at, so a Coolify deploy that
         *       forgot to run migrations is one curl away from being
         *       caught;
         *     * DB connectivity — a trivial ``SELECT 1`` round-trip;
         *     * oldest pending dispatch — surfaces a stuck queue (worker
         *       crashed, SMTP outage, etc.) before it shows up in user
         *       complaints.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserOut */
        AdminUserOut: {
            /** Chapter Id */
            chapter_id: string | null;
            /** Chapter Name */
            chapter_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Is Approved */
            is_approved: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ApproveUserRequest */
        ApproveUserRequest: {
            /** Chapter Id */
            chapter_id: string;
        };
        /** AssignChapterRequest */
        AssignChapterRequest: {
            /** Chapter Id */
            chapter_id: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * ChapterArchiveRequest
         * @description Optional reassignment targets when archiving a chapter. Both
         *     default to None — neither is mandatory; rows that aren't
         *     reassigned simply stay linked to the about-to-be-archived
         *     entity_id (events become invisible until restore, users still
         *     have a chapter_id pointing at the archived chapter).
         */
        ChapterArchiveRequest: {
            /** Reassign Events To */
            reassign_events_to?: string | null;
            /** Reassign Users To */
            reassign_users_to?: string | null;
        };
        /** ChapterCreate */
        ChapterCreate: {
            /** Name */
            name: string;
        };
        /**
         * ChapterOut
         * @description One chapter, current or archived. ``id`` is the entity_id (the
         *     stable logical identifier, what FKs from events / users point at).
         *     ``archived`` mirrors ``valid_until IS NOT NULL`` so the frontend
         *     doesn't need to inspect timestamps.
         */
        ChapterOut: {
            /** Archived */
            archived: boolean;
            /** City */
            city: string | null;
            /** City Lat */
            city_lat: number | null;
            /** City Lon */
            city_lon: number | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ChapterPatch
         * @description Partial update for a chapter. Either field may be omitted;
         *     the city tuple is all-or-nothing — passing ``city`` requires
         *     ``city_lat``/``city_lon`` (and vice versa) so we never end up
         *     with a city display name that has no coordinates.
         */
        ChapterPatch: {
            /** City */
            city?: string | null;
            /** City Lat */
            city_lat?: number | null;
            /** City Lon */
            city_lon?: number | null;
            /** Name */
            name?: string | null;
        };
        /**
         * ChapterUsageOut
         * @description How many users / events are currently assigned to this
         *     chapter. Used by the delete dialog so the admin sees what
         *     happens to dependents before confirming.
         */
        ChapterUsageOut: {
            /** Events */
            events: number;
            /** Users */
            users: number;
        };
        /**
         * EmailHealthOut
         * @description Aggregate of one channel's email delivery status across an
         *     event's signups. Counts always sum to ``signup_count``.
         */
        EmailHealthOut: {
            /** Bounced */
            bounced: number;
            /** Complaint */
            complaint: number;
            /** Failed */
            failed: number;
            /** Not Applicable */
            not_applicable: number;
            /** Pending */
            pending: number;
            /** Sent */
            sent: number;
        };
        /** EventCreate */
        EventCreate: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Help Options */
            help_options?: string[];
            /** Latitude */
            latitude?: number | null;
            /**
             * Locale
             * @default nl
             * @enum {string}
             */
            locale: "nl" | "en";
            /** Location */
            location: string;
            /** Longitude */
            longitude?: number | null;
            /** Name */
            name: string;
            /**
             * Questionnaire Enabled
             * @default true
             */
            questionnaire_enabled: boolean;
            /**
             * Reminder Enabled
             * @default false
             */
            reminder_enabled: boolean;
            /** Source Options */
            source_options: string[];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Topic */
            topic?: string | null;
        };
        /** EventOut */
        EventOut: {
            /** Chapter Id */
            chapter_id: string | null;
            /** Chapter Name */
            chapter_name: string | null;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Help Options */
            help_options: string[];
            /** Id */
            id: string;
            /** Latitude */
            latitude: number | null;
            /**
             * Locale
             * @enum {string}
             */
            locale: "nl" | "en";
            /** Location */
            location: string;
            /** Longitude */
            longitude: number | null;
            /** Name */
            name: string;
            /** Questionnaire Enabled */
            questionnaire_enabled: boolean;
            /** Reminder Enabled */
            reminder_enabled: boolean;
            /** Signup Count */
            signup_count: number;
            /** Slug */
            slug: string;
            /** Source Options */
            source_options: string[];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Topic */
            topic: string | null;
        };
        /**
         * EventStatsOut
         * @description Organiser-only aggregate. Never includes individual signups.
         */
        EventStatsOut: {
            /** By Help */
            by_help: {
                [key: string]: number;
            };
            /** By Source */
            by_source: {
                [key: string]: number;
            };
            /** Total Attendees */
            total_attendees: number;
            /** Total Signups */
            total_signups: number;
        };
        /** FeedbackAnswerIn */
        FeedbackAnswerIn: {
            /** Answer Int */
            answer_int?: number | null;
            /** Answer Text */
            answer_text?: string | null;
            /** Question Id */
            question_id: string;
        };
        /**
         * FeedbackFormOut
         * @description Public payload for GET /feedback/{token} — what the questionnaire
         *     page renders. Includes minimal event context so the page can show
         *     the user which event they're giving feedback on.
         */
        FeedbackFormOut: {
            /**
             * Event Locale
             * @enum {string}
             */
            event_locale: "nl" | "en";
            /** Event Name */
            event_name: string;
            /** Event Slug */
            event_slug: string;
            /** Questions */
            questions: components["schemas"]["FeedbackQuestionOut"][];
        };
        /**
         * FeedbackQuestionOut
         * @description Question shape for the public form. The frontend resolves the
         *     prompt + labels from i18n using ``key``.
         */
        FeedbackQuestionOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Ordinal */
            ordinal: number;
            /** Required */
            required: boolean;
        };
        /**
         * FeedbackQuestionSummary
         * @description Per-question aggregate. ``rating_distribution`` is a 1..5 array
         *     when kind=='rating' (counts at each scale point), or null. ``texts``
         *     is the list of free-text answers when kind=='text', or null.
         */
        FeedbackQuestionSummary: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Question Id */
            question_id: string;
            /** Rating Average */
            rating_average?: number | null;
            /** Rating Distribution */
            rating_distribution?: number[] | null;
            /** Response Count */
            response_count: number;
            /** Texts */
            texts?: string[] | null;
        };
        /**
         * FeedbackSubmissionOut
         * @description One submission as a flat record — keyed by ``question.key`` so
         *     a CSV consumer can map columns by question identifier without
         *     needing the questions table. Rating values surface as the int;
         *     text answers as the string. Missing answers are absent from
         *     ``answers``. ``submission_id`` is the random per-submission id
         *     that has no link back to a signup (privacy contract).
         */
        FeedbackSubmissionOut: {
            /** Answers */
            answers: {
                [key: string]: number | string;
            };
            /** Submission Id */
            submission_id: string;
        };
        /** FeedbackSubmitIn */
        FeedbackSubmitIn: {
            /** Answers */
            answers: components["schemas"]["FeedbackAnswerIn"][];
        };
        /**
         * FeedbackSummaryOut
         * @description Organiser-only feedback summary for an event. ``email_health``
         *     is keyed by channel name (``reminder`` / ``feedback``) so the
         *     dashboard can surface delivery health for each side-by-side.
         */
        FeedbackSummaryOut: {
            /** Email Health */
            email_health: {
                [key: string]: components["schemas"]["EmailHealthOut"];
            };
            /** Questions */
            questions: components["schemas"]["FeedbackQuestionSummary"][];
            /** Response Rate */
            response_rate: number;
            /** Signup Count */
            signup_count: number;
            /** Submission Count */
            submission_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinkSent
         * @description Boring 200 response so /login-link and /register don't leak
         *     whether an email exists.
         */
        LinkSent: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** LoginLinkRequest */
        LoginLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * LoginRequest
         * @description Redeems a magic-link token. The token was minted by
         *     ``/auth/login-link`` (existing user) or ``/auth/register`` (new
         *     user); both flows funnel into this single redemption endpoint.
         */
        LoginRequest: {
            /** Token */
            token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
        };
        /**
         * SignupAck
         * @description Public response after a successful signup. Returns nothing
         *     identifying — just confirms the booking landed.
         */
        SignupAck: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** SignupCreate */
        SignupCreate: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Help Choices */
            help_choices?: string[];
            /** Party Size */
            party_size: number;
            /** Source Choice */
            source_choice?: string | null;
        };
        /**
         * SignupSummaryOut
         * @description A single signup as seen on the organiser's details page.
         *     Deliberately minimal — name and headcount only. Never email,
         *     source, or feedback-email status; those exist on the model but
         *     are private to the worker.
         */
        SignupSummaryOut: {
            /** Display Name */
            display_name: string | null;
            /** Help Choices */
            help_choices: string[];
            /** Party Size */
            party_size: number;
        };
        /** UserOut */
        UserOut: {
            /** Chapter Id */
            chapter_id: string | null;
            /** Chapter Name */
            chapter_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Is Approved */
            is_approved: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                pending?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__entity_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_user_api_v1_admin_users__entity_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_chapter_api_v1_admin_users__entity_id__assign_chapter_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignChapterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demote_user_api_v1_admin_users__entity_id__demote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_user_api_v1_admin_users__entity_id__promote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_link_api_v1_auth_login_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkSent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkSent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_api_v1_chapters_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chapter_api_v1_chapters_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_chapter_api_v1_chapters__entity_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ChapterArchiveRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_chapter_api_v1_chapters__entity_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_chapter_api_v1_chapters__entity_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chapter_usage_api_v1_chapters__entity_id__usage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterUsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_archived_events_api_v1_events_archived_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_slug_api_v1_events_by_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_preview_api_v1_events_by_slug__slug__email_preview__channel__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_ics_api_v1_events_by_slug__slug__event_ics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_form_preview_api_v1_events_by_slug__slug__feedback_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_qr_api_v1_events_by_slug__slug__qr_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_signup_api_v1_events_by_slug__slug__signups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_v1_events__entity_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_event_api_v1_events__entity_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_submissions_api_v1_events__entity_id__feedback_submissions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSubmissionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_summary_api_v1_events__entity_id__feedback_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_event_api_v1_events__entity_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_emails_now_api_v1_events__entity_id__send_emails__channel__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_signups_api_v1_events__entity_id__signups_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stats_api_v1_events__entity_id__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_feedback_questions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_form_api_v1_feedback__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackFormOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback__token__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scaleway_email_event_api_v1_webhooks_scaleway_email_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Scaleway-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
