/**
 * Chore-roster composables ("Takenroosters").
 *
 * The chapter-scoped CRUD surface is generated by the shared
 * ``createEntityCrud`` factory; there are no roster-specific reads yet
 * (the schedule / volunteers endpoints arrive with their data in task
 * 06). ``useChoresClipboard`` lives in its own file, like the other
 * per-entity clipboard wrappers.
 */

import { listOf } from "@/api/queries";
import type {
  RosterCreate,
  RosterListOut,
  RosterOut,
  RosterUpdate,
} from "@/api/types";
import { createEntityCrud } from "@/composables/createEntityCrud";

export type { RosterCreate, RosterListOut, RosterOut, RosterUpdate };

const crud = createEntityCrud<RosterListOut, RosterOut, RosterCreate, RosterUpdate>({
  resource: "chores",
});

export const useRosterList = crud.useList;
export const rosterList = listOf<RosterListOut>;
export const useArchivedRosters = crud.useArchived;
export const useRoster = crud.useSingle;
export const useCreateRoster = crud.useCreate;
export const useUpdateRoster = crud.useUpdate;
export const useArchiveRoster = crud.useArchive;
export const useRestoreRoster = crud.useRestore;
export const useDeleteRoster = crud.useDelete;
