/**
 * Chore-roster composables ("Takenroosters").
 *
 * The chapter-scoped CRUD surface is generated by the shared
 * ``createEntityCrud`` factory; there are no roster-specific reads yet
 * (the schedule / volunteers endpoints arrive with their data in task
 * 06). ``useChoresClipboard`` lives in its own file, like the other
 * per-entity clipboard wrappers.
 */

import { type MaybeRef, unref } from "vue";

import { listOf, useApiQuery } from "@/api/queries";
import type {
  ChoreAccountability,
  ChoreCalendar,
  ChoreSchedule,
  RosterCreate,
  RosterListOut,
  RosterOut,
  RosterUpdate,
  VolunteerSummary,
} from "@/api/types";
import { createEntityCrud } from "@/composables/createEntityCrud";

export type { RosterCreate, RosterListOut, RosterOut, RosterUpdate };

const crud = createEntityCrud<RosterListOut, RosterOut, RosterCreate, RosterUpdate>({
  resource: "chore",
});

export const useRosterList = crud.useList;
export const rosterList = listOf<RosterListOut>;
export const useArchivedRosters = crud.useArchived;
export const useRoster = crud.useSingle;
export const useCreateRoster = crud.useCreate;
export const useUpdateRoster = crud.useUpdate;
export const useArchiveRoster = crud.useArchive;
export const useRestoreRoster = crud.useRestore;
export const useDeleteRoster = crud.useDelete;

// --- Roster-specific reads (shifts arrive with task 06) ---

export function useRosterVolunteers(rosterId: MaybeRef<string>) {
  return useApiQuery<VolunteerSummary[]>(
    () => ["chore", unref(rosterId), "volunteers"],
    () => `/api/v1/chore/${unref(rosterId)}/volunteers`,
  );
}

export function useRosterAccountability(rosterId: MaybeRef<string>) {
  return useApiQuery<ChoreAccountability[]>(
    () => ["chore", unref(rosterId), "accountability"],
    () => `/api/v1/chore/${unref(rosterId)}/accountability`,
  );
}

export function useRosterSchedule(rosterId: MaybeRef<string>) {
  return useApiQuery<ChoreSchedule>(
    () => ["chore", unref(rosterId), "schedule"],
    () => `/api/v1/chore/${unref(rosterId)}/schedule`,
  );
}

/** The roster as a per-chore calendar for one ``YYYY-MM`` month. */
export function useRosterCalendar(rosterId: MaybeRef<string>, month: MaybeRef<string>) {
  return useApiQuery<ChoreCalendar[]>(
    () => ["chore", unref(rosterId), "calendar", unref(month)],
    () => `/api/v1/chore/${unref(rosterId)}/calendar?month=${unref(month)}`,
  );
}

/** The post-"fold in now" calendar for one month, with changed days flagged.
 * Fetched only while the fold-in dialog is open (``enabled``). */
export function useRebalancePreviewCalendar(
  rosterId: MaybeRef<string>,
  month: MaybeRef<string>,
  enabled: MaybeRef<boolean>,
) {
  return useApiQuery<ChoreCalendar[]>(
    () => ["chore", unref(rosterId), "rebalance-preview", unref(month)],
    () => `/api/v1/chore/${unref(rosterId)}/rebalance/preview?month=${unref(month)}`,
    { enabled },
  );
}
