/**
 * Datepoll composables.
 *
 * Dates-only availability polls that mirror the events/form
 * resource: chapter-scoped CRUD with active/archived lifecycle,
 * public-by-slug submission, per-date response aggregates.
 *
 * Reads ride ``useApiQuery``; writes invalidate the affected list
 * caches. Mirrors ``useForms.ts`` one-to-one.
 */

import { type MaybeRef, unref } from "vue";

import { get } from "@/api/client";
import { listOf, useApiQuery } from "@/api/queries";
import { createEntityCrud } from "@/composables/createEntityCrud";
import type {
  DatepollCreate,
  DatepollListOut,
  DatepollOut,
  DatepollSlotOut,
  DatepollSubmission,
  DatepollSummary,
  DatepollUpdate,
  PublicDatepollOut,
} from "@/api/types";

export type {
  DatepollCreate,
  DatepollListOut,
  DatepollOut,
  DatepollSlotOut,
  DatepollSubmission,
  DatepollSummary,
  DatepollUpdate,
  PublicDatepollOut,
};

// The chapter-scoped CRUD surface is generated by the shared factory;
// only the datepoll-specific reads + public submit live below.
const crud = createEntityCrud<DatepollListOut, DatepollOut, DatepollCreate, DatepollUpdate>({
  resource: "datepoll",
});

// --- Reads ---------------------------------------------------------

export const useDatepollList = crud.useList;
export const datepollList = listOf<DatepollListOut>;
export const useArchivedDatepolls = crud.useArchived;
export const useDatepoll = crud.useSingle;

export function useDatepollSummary(datepollId: MaybeRef<string>) {
  return useApiQuery<DatepollSummary>(
    () => ["datepoll", unref(datepollId), "summary"],
    () => `/api/v1/datepoll/${unref(datepollId)}/summary`,
  );
}

/** Per-submission rows — CSV source. One-shot fetch, not a query. */
export function fetchDatepollSubmissions(datepollId: string) {
  return get<DatepollSubmission[]>(`/api/v1/datepoll/${datepollId}/submissions`);
}

// --- Public read (by slug) -----------------------------------------

export function usePublicDatepoll(slug: MaybeRef<string>, enabled?: MaybeRef<boolean>) {
  return useApiQuery<PublicDatepollOut>(
    () => ["datepoll", "by-slug", unref(slug)],
    () => `/api/v1/datepoll/by-slug/${encodeURIComponent(unref(slug))}`,
    { enabled },
  );
}

// --- Writes --------------------------------------------------------
// CRUD mutations come straight from the factory. ``useUpdateDatepoll``
// takes ``{ id, payload }``; archive/restore/delete take a bare id.

export const useCreateDatepoll = crud.useCreate;
export const useUpdateDatepoll = crud.useUpdate;
export const useArchiveDatepoll = crud.useArchive;
export const useRestoreDatepoll = crud.useRestore;
export const useDeleteDatepoll = crud.useDelete;
