/**
 * Form composables, for every product in the forms table.
 *
 * A questionnaire, a quiz and a kompas differ by what an answer means
 * (nothing, a key, a pole) and by how the questions are walked through
 * (``docs/design-quizzes.md``, ``docs/design-kompas.md``), and by
 * nothing at all at this layer: the same CRUD, the same summary, the
 * same by-slug read, against ``/api/v1/form``, ``/api/v1/quiz`` or
 * ``/api/v1/compass``. So this file builds the surface once and
 * hands out one per product, and the organiser pages ask
 * ``useFormsApi()`` which one they are on rather than importing one by
 * name.
 *
 * Reads (list, archived, single, summary, by-slug) ride
 * ``useApiQuery``. Writes (create, update, archive, restore,
 * delete, public submit) are mutations that invalidate the
 * affected list caches.
 */

import { useMutation } from "@tanstack/vue-query";
import { type MaybeRef, unref } from "vue";
import { useRoute } from "vue-router";

import { get, post } from "@/api/client";
import { listOf, useApiQuery } from "@/api/queries";
import { createEntityCrud } from "@/composables/createEntityCrud";
import type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
} from "@/api/types";

export type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
};

/** The products, and the API prefix each one lives under. */
export type FormResource = "form" | "quiz" | "compass";

/** Every resource, so a caller that has to cover all of them (the
 *  copy test, a route table) enumerates rather than remembers. */
export const FORM_RESOURCES: readonly FormResource[] = ["form", "quiz", "compass"];

function makeApi(resource: FormResource) {
  // The chapter-scoped CRUD surface (list / archived / single / create /
  // update / archive / restore / delete) is generated by the shared
  // factory; only the form-specific reads + public submit are here.
  const crud = createEntityCrud<FormListOut, FormOut, FormCreate, FormUpdate>({ resource });
  const base = `/api/v1/${resource}`;

  return {
    resource,
    useList: crud.useList,
    useArchived: crud.useArchived,
    useSingle: crud.useSingle,
    useCreate: crud.useCreate,
    useUpdate: crud.useUpdate,
    useArchive: crud.useArchive,
    useRestore: crud.useRestore,
    useDelete: crud.useDelete,

    useSummary(formId: MaybeRef<string>) {
      return useApiQuery<FormSummary>(
        () => [resource, unref(formId), "summary"],
        () => `${base}/${unref(formId)}/summary`,
      );
    },

    /** Per-submission rows — CSV source. Not a Vue Query (one-shot
     * download), just a thin fetch helper. */
    fetchSubmissions(formId: string) {
      return get<FormSubmission[]>(`${base}/${formId}/submissions`);
    },

    /** Public fetch by slug. Doesn't require auth. */
    usePublic(slug: MaybeRef<string>, enabled?: MaybeRef<boolean>) {
      return useApiQuery<PublicFormOut>(
        () => [resource, "by-slug", unref(slug)],
        () => `${base}/by-slug/${encodeURIComponent(unref(slug))}`,
        { enabled },
      );
    },

    useSubmit() {
      return useMutation({
        mutationFn: (vars: { slug: string; payload: FormSubmit }) =>
          post<FormSubmitAck>(`${base}/by-slug/${encodeURIComponent(vars.slug)}/submit`, vars.payload),
      });
    },
  };
}

export const formsApi = makeApi("form");
export const quizzesApi = makeApi("quiz");
export const compassesApi = makeApi("compass");

const BY_RESOURCE: Record<FormResource, ReturnType<typeof makeApi>> = {
  form: formsApi,
  quiz: quizzesApi,
  compass: compassesApi,
};

/** Which product an organiser page is on. The route says so
 * (``meta.resource``); the four pages are registered once per product,
 * because everything they render is the same. An absent or unknown
 * value is the questionnaire, which is the base vocabulary. */
export function useFormsApi() {
  const route = useRoute();
  const resource = route.meta.resource as FormResource | undefined;
  return (resource && BY_RESOURCE[resource]) || formsApi;
}

// --- Named exports, for the code that only ever means a questionnaire.

export const useFormList = formsApi.useList;
export const formList = listOf<FormListOut>;
export const useArchivedForms = formsApi.useArchived;
export const useForm = formsApi.useSingle;
export const useFormSummary = formsApi.useSummary;
export const fetchFormSubmissions = formsApi.fetchSubmissions;
export const usePublicForm = formsApi.usePublic;
export const useCreateForm = formsApi.useCreate;
export const useUpdateForm = formsApi.useUpdate;
export const useArchiveForm = formsApi.useArchive;
export const useRestoreForm = formsApi.useRestore;
export const useDeleteForm = formsApi.useDelete;
export const useSubmitForm = formsApi.useSubmit;
