/**
 * Form composables, for both products in the forms table.
 *
 * A questionnaire and a quiz differ by an answer key, a score and how
 * the questions are walked through (``docs/design-quizzes.md``), and by
 * nothing at all at this layer: the same CRUD, the same summary, the
 * same by-slug read, against ``/api/v1/forms`` or ``/api/v1/quizzes``.
 * So this file builds the surface once and hands out two of them, and
 * the organiser pages ask ``useFormsApi()`` which one they are on
 * rather than importing one by name.
 *
 * Reads (list, archived, single, summary, by-slug) ride
 * ``useApiQuery``. Writes (create, update, archive, restore,
 * delete, public submit) are mutations that invalidate the
 * affected list caches.
 */

import { useMutation } from "@tanstack/vue-query";
import { type MaybeRef, unref } from "vue";
import { useRoute } from "vue-router";

import { get, post } from "@/api/client";
import { listOf, useApiQuery } from "@/api/queries";
import { createEntityCrud } from "@/composables/createEntityCrud";
import type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
} from "@/api/types";

export type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
};

/** The two products, and the API prefix each one lives under. */
export type FormResource = "forms" | "quizzes";

function makeApi(resource: FormResource) {
  // The chapter-scoped CRUD surface (list / archived / single / create /
  // update / archive / restore / delete) is generated by the shared
  // factory; only the form-specific reads + public submit are here.
  const crud = createEntityCrud<FormListOut, FormOut, FormCreate, FormUpdate>({ resource });
  const base = `/api/v1/${resource}`;

  return {
    resource,
    useList: crud.useList,
    useArchived: crud.useArchived,
    useSingle: crud.useSingle,
    useCreate: crud.useCreate,
    useUpdate: crud.useUpdate,
    useArchive: crud.useArchive,
    useRestore: crud.useRestore,
    useDelete: crud.useDelete,

    useSummary(formId: MaybeRef<string>) {
      return useApiQuery<FormSummary>(
        () => [resource, unref(formId), "summary"],
        () => `${base}/${unref(formId)}/summary`,
      );
    },

    /** Per-submission rows — CSV source. Not a Vue Query (one-shot
     * download), just a thin fetch helper. */
    fetchSubmissions(formId: string) {
      return get<FormSubmission[]>(`${base}/${formId}/submissions`);
    },

    /** Public fetch by slug. Doesn't require auth. */
    usePublic(slug: MaybeRef<string>, enabled?: MaybeRef<boolean>) {
      return useApiQuery<PublicFormOut>(
        () => [resource, "by-slug", unref(slug)],
        () => `${base}/by-slug/${encodeURIComponent(unref(slug))}`,
        { enabled },
      );
    },

    useSubmit() {
      return useMutation({
        mutationFn: (vars: { slug: string; payload: FormSubmit }) =>
          post<FormSubmitAck>(`${base}/by-slug/${encodeURIComponent(vars.slug)}/submit`, vars.payload),
      });
    },
  };
}

export const formsApi = makeApi("forms");
export const quizzesApi = makeApi("quizzes");

/** Which of the two an organiser page is on. The route says so
 * (``meta.resource``); the four pages are registered twice, once per
 * product, because everything they render is the same. */
export function useFormsApi() {
  const route = useRoute();
  return (route.meta.resource as FormResource | undefined) === "quizzes" ? quizzesApi : formsApi;
}

// --- Named exports, for the code that only ever means a questionnaire.

export const useFormList = formsApi.useList;
export const formList = listOf<FormListOut>;
export const useArchivedForms = formsApi.useArchived;
export const useForm = formsApi.useSingle;
export const useFormSummary = formsApi.useSummary;
export const fetchFormSubmissions = formsApi.fetchSubmissions;
export const usePublicForm = formsApi.usePublic;
export const useCreateForm = formsApi.useCreate;
export const useUpdateForm = formsApi.useUpdate;
export const useArchiveForm = formsApi.useArchive;
export const useRestoreForm = formsApi.useRestore;
export const useDeleteForm = formsApi.useDelete;
export const useSubmitForm = formsApi.useSubmit;
