/**
 * Form composables.
 *
 * Standalone questionnaires that mirror the events resource:
 * chapter-scoped CRUD with active/archived lifecycle, public-by-
 * slug submission, per-question response aggregates.
 *
 * Reads (list, archived, single, summary, by-slug) ride
 * ``useApiQuery``. Writes (create, update, archive, restore,
 * delete, public submit) are mutations that invalidate the
 * affected list caches.
 */

import { useMutation } from "@tanstack/vue-query";
import { type MaybeRef, unref } from "vue";

import { get, post } from "@/api/client";
import { listOf, useApiQuery } from "@/api/queries";
import { createEntityCrud } from "@/composables/createEntityCrud";
import type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
} from "@/api/types";

export type {
  FormCreate,
  FormListOut,
  FormOut,
  FormQuestionIn,
  FormQuestionOut,
  FormSubmit,
  FormSubmitAck,
  FormSubmission,
  FormSummary,
  FormUpdate,
  PublicFormOut,
};

// The chapter-scoped CRUD surface (list / archived / single / create /
// update / archive / restore / delete) is generated by the shared
// factory; only the form-specific reads + public submit live below.
const crud = createEntityCrud<FormListOut, FormOut, FormCreate, FormUpdate>({
  resource: "forms",
});

// --- Reads ---------------------------------------------------------

export const useFormList = crud.useList;
export const formList = listOf<FormListOut>;
export const useArchivedForms = crud.useArchived;
export const useForm = crud.useSingle;

export function useFormSummary(formId: MaybeRef<string>) {
  return useApiQuery<FormSummary>(
    () => ["forms", unref(formId), "summary"],
    () => `/api/v1/forms/${unref(formId)}/summary`,
  );
}

/** Per-submission rows — CSV source. Not a Vue Query (one-shot
 * download), just a thin fetch helper. */
export function fetchFormSubmissions(formId: string) {
  return get<FormSubmission[]>(`/api/v1/forms/${formId}/submissions`);
}

// --- Public read (by slug) -----------------------------------------

/** Public form fetch. Doesn't require auth. */
export function usePublicForm(slug: MaybeRef<string>, enabled?: MaybeRef<boolean>) {
  return useApiQuery<PublicFormOut>(
    () => ["forms", "by-slug", unref(slug)],
    () => `/api/v1/forms/by-slug/${encodeURIComponent(unref(slug))}`,
    { enabled },
  );
}

// --- Writes --------------------------------------------------------
// CRUD mutations come straight from the factory. ``useUpdateForm`` takes
// ``{ id, payload }``; archive/restore/delete take a bare form id.

export const useCreateForm = crud.useCreate;
export const useUpdateForm = crud.useUpdate;
export const useArchiveForm = crud.useArchive;
export const useRestoreForm = crud.useRestore;
export const useDeleteForm = crud.useDelete;

// --- Public submit -------------------------------------------------

export function useSubmitForm() {
  return useMutation({
    mutationFn: (vars: { slug: string; payload: FormSubmit }) =>
      post<FormSubmitAck>(
        `/api/v1/forms/by-slug/${encodeURIComponent(vars.slug)}/submit`,
        vars.payload,
      ),
  });
}
