"""initial schema

Revision ID: 029e6226f08b
Revises: 
Create Date: 2026-04-30 21:14:15.092988
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '029e6226f08b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_lat', sa.Float(), nullable=True),
    sa.Column('city_lon', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_deleted_at'), 'chapters', ['deleted_at'], unique=False)
    op.create_index('uq_chapters_name_live', 'chapters', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_chapter_id'), 'users', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('uq_users_email_live', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('events',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_options', sa.JSON(), nullable=False),
    sa.Column('help_options', sa.JSON(), nullable=False),
    sa.Column('feedback_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_archived_at'), 'events', ['archived_at'], unique=False)
    op.create_index('ix_events_archived_chapter', 'events', ['archived_at', 'chapter_id'], unique=False)
    op.create_index(op.f('ix_events_chapter_id'), 'events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('login_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_token'), 'login_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_login_tokens_user_id'), 'login_tokens', ['user_id'], unique=False)
    op.create_table('email_dispatches',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('REMINDER', 'FEEDBACK', name='email_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='email_status'), nullable=False),
    sa.Column('encrypted_email', sa.LargeBinary(), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispatches_event_channel_status', 'email_dispatches', ['event_id', 'channel', 'status'], unique=False)
    op.create_index(op.f('ix_email_dispatches_event_id'), 'email_dispatches', ['event_id'], unique=False)
    op.create_table('feedback_responses',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('question_key', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_responses_event_id'), 'feedback_responses', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_responses_submission_id'), 'feedback_responses', ['submission_id'], unique=False)
    op.create_table('feedback_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_tokens_event_id'), 'feedback_tokens', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_tokens_token'), 'feedback_tokens', ['token'], unique=True)
    op.create_table('signups',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('source_choice', sa.Text(), nullable=True),
    sa.Column('help_choices', sa.JSON(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_event_id'), 'signups', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signups_event_id'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_feedback_tokens_token'), table_name='feedback_tokens')
    op.drop_index(op.f('ix_feedback_tokens_event_id'), table_name='feedback_tokens')
    op.drop_table('feedback_tokens')
    op.drop_index(op.f('ix_feedback_responses_submission_id'), table_name='feedback_responses')
    op.drop_index(op.f('ix_feedback_responses_event_id'), table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index(op.f('ix_email_dispatches_event_id'), table_name='email_dispatches')
    op.drop_index('ix_dispatches_event_channel_status', table_name='email_dispatches')
    op.drop_table('email_dispatches')
    op.drop_index(op.f('ix_login_tokens_user_id'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_token'), table_name='login_tokens')
    op.drop_table('login_tokens')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_chapter_id'), table_name='events')
    op.drop_index('ix_events_archived_chapter', table_name='events')
    op.drop_index(op.f('ix_events_archived_at'), table_name='events')
    op.drop_table('events')
    op.drop_index('uq_users_email_live', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_chapter_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_chapters_name_live', table_name='chapters', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_chapters_deleted_at'), table_name='chapters')
    op.drop_table('chapters')
    # Drop the named ENUM types — autogenerate creates them implicitly
    # when the columns are created but doesn't track them for the
    # downgrade, leaving CREATE TYPE conflicts on round-trip.
    sa.Enum(name='email_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='email_channel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
