"""add questionnaire_enabled to events

Revision ID: 04f3e8d1997d
Revises: dd24331630ae
Create Date: 2026-04-26 13:03:23.386934
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '04f3e8d1997d'
down_revision: str | None = 'dd24331630ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing rows default to questionnaire enabled — preserves the
    # current behaviour for events created before the toggle existed.
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('questionnaire_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('questionnaire_enabled')

    # ### end Alembic commands ###
