"""events.listed + chapters.slug

Revision ID: 0526d200e06b
Revises: 372b3d4c52d2
Create Date: 2026-07-08 18:13:08.861352
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0526d200e06b'
down_revision: str | None = '372b3d4c52d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ``events.listed``: existing events default to listed.
    op.add_column(
        "events",
        sa.Column("listed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )

    # ``chapters.slug``: add nullable, backfill a unique kebab slug from
    # each chapter's name (same helper the app uses, so shape + accent
    # handling match), then enforce NOT NULL + the live-scoped unique
    # index.
    from backend.services.slug import chapter_slug

    op.add_column("chapters", sa.Column("slug", sa.Text(), nullable=True))
    conn = op.get_bind()
    used: set[str] = set()
    for cid, name in conn.execute(sa.text("SELECT id, name FROM chapters")).fetchall():
        base = chapter_slug(name or "afdeling")
        slug = base
        n = 2
        while slug in used:
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        conn.execute(
            sa.text("UPDATE chapters SET slug = :s WHERE id = :id"), {"s": slug, "id": cid}
        )
    op.alter_column("chapters", "slug", nullable=False)
    op.create_index(
        "uq_chapters_slug_live",
        "chapters",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'listed')
    op.drop_index('uq_chapters_slug_live', table_name='chapters', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('chapters', 'slug')
    # ### end Alembic commands ###
