"""roster commit_horizon_days + activated_at

Revision ID: 05b96c6951f1
Revises: f0692bb588f6
Create Date: 2026-07-01 11:35:23.499757
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '05b96c6951f1'
down_revision: str | None = 'f0692bb588f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosters', sa.Column('commit_horizon_days', sa.Integer(), nullable=False))
    op.add_column('rosters', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosters', 'activated_at')
    op.drop_column('rosters', 'commit_horizon_days')
    # ### end Alembic commands ###
