"""initial schema

Revision ID: 09310a8cd04a
Revises: 
Create Date: 2026-04-28 19:07:52.298022
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '09310a8cd04a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('chapters',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_lat', sa.Float(), nullable=True),
    sa.Column('city_lon', sa.Float(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('change_kind', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_entity_id'), 'chapters', ['entity_id'], unique=False)
    op.create_index(op.f('ix_chapters_valid_until'), 'chapters', ['valid_until'], unique=False)
    op.create_table('events',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_options', sa.JSON(), nullable=False),
    sa.Column('help_options', sa.JSON(), nullable=False),
    sa.Column('questionnaire_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('change_kind', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_archived_at'), 'events', ['archived_at'], unique=False)
    op.create_index(op.f('ix_events_chapter_id'), 'events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=False)
    op.create_index(op.f('ix_events_valid_until'), 'events', ['valid_until'], unique=False)
    op.create_index('uq_events_slug_current', 'events', ['slug'], unique=True, postgresql_where=sa.text('valid_until IS NULL'))
    op.create_table('feedback_questions',
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('signup_email_dispatches',
    sa.Column('signup_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('REMINDER', 'FEEDBACK', name='email_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'BOUNCED', 'COMPLAINT', name='email_status'), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signup_id', 'channel', name='uq_dispatches_signup_channel')
    )
    op.create_index('ix_dispatches_channel_status', 'signup_email_dispatches', ['channel', 'status'], unique=False)
    op.create_index('ix_dispatches_message_id', 'signup_email_dispatches', ['message_id'], unique=False)
    op.create_index(op.f('ix_signup_email_dispatches_signup_id'), 'signup_email_dispatches', ['signup_id'], unique=False)
    op.create_table('signups',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('source_choice', sa.Text(), nullable=True),
    sa.Column('help_choices', sa.JSON(), nullable=False),
    sa.Column('encrypted_email', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_event_id'), 'signups', ['event_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('change_kind', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_chapter_id'), 'users', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_entity_id'), 'users', ['entity_id'], unique=False)
    op.create_index(op.f('ix_users_valid_until'), 'users', ['valid_until'], unique=False)
    op.create_index('uq_users_email_current', 'users', ['email'], unique=True, postgresql_where=sa.text('valid_until IS NULL'))
    op.create_table('feedback_responses',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_responses_event_id'), 'feedback_responses', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_responses_submission_id'), 'feedback_responses', ['submission_id'], unique=False)
    op.create_table('feedback_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('signup_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_tokens_event_id'), 'feedback_tokens', ['event_id'], unique=False)
    op.create_index(op.f('ix_feedback_tokens_token'), 'feedback_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_tokens_token'), table_name='feedback_tokens')
    op.drop_index(op.f('ix_feedback_tokens_event_id'), table_name='feedback_tokens')
    op.drop_table('feedback_tokens')
    op.drop_index(op.f('ix_feedback_responses_submission_id'), table_name='feedback_responses')
    op.drop_index(op.f('ix_feedback_responses_event_id'), table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index('uq_users_email_current', table_name='users', postgresql_where=sa.text('valid_until IS NULL'))
    op.drop_index(op.f('ix_users_valid_until'), table_name='users')
    op.drop_index(op.f('ix_users_entity_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_chapter_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signups_event_id'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_signup_email_dispatches_signup_id'), table_name='signup_email_dispatches')
    op.drop_index('ix_dispatches_message_id', table_name='signup_email_dispatches')
    op.drop_index('ix_dispatches_channel_status', table_name='signup_email_dispatches')
    op.drop_table('signup_email_dispatches')
    op.drop_table('feedback_questions')
    op.drop_index('uq_events_slug_current', table_name='events', postgresql_where=sa.text('valid_until IS NULL'))
    op.drop_index(op.f('ix_events_valid_until'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_chapter_id'), table_name='events')
    op.drop_index(op.f('ix_events_archived_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_chapters_valid_until'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_entity_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
