"""indexes that match the queries

Four composites the code actually asks for, and six single-column
indexes that were a second copy of a composite's leading column or of
nothing at all. docs/design-indexing.md has the reasoning per table.

Production statistics could not settle this: every index there reports
zero scans, because the tables hold a handful of rows and Postgres
sequentially scans them all. The shapes below are matched to the queries
in the code, which is what will still be true when the tables are big
enough for the planner to change its mind.

Revision ID: 0a7d0d6080d3
Revises: f140412eb2b1
Create Date: 2026-08-29 09:55:19.675246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0a7d0d6080d3'
down_revision: str | None = 'f140412eb2b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datepolls_created_by'), table_name='datepolls')
    op.create_index('ix_datepolls_tenant_chapter_created', 'datepolls', ['tenant_id', 'chapter_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_email_dispatches_occurrence_id'), table_name='email_dispatches')
    op.drop_index(op.f('ix_email_send_counts_day'), table_name='email_send_counts')
    op.create_index('ix_email_send_counts_tenant_day', 'email_send_counts', ['tenant_id', 'day'], unique=False)
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.create_index('ix_events_tenant_chapter_created', 'events', ['tenant_id', 'chapter_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_forms_created_by'), table_name='forms')
    op.create_index('ix_forms_tenant_mode_chapter_created', 'forms', ['tenant_id', 'mode', 'chapter_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_occurrences_event_id'), table_name='occurrences')
    op.create_index('ix_occurrences_tenant_starts', 'occurrences', ['tenant_id', 'starts_at'], unique=False)
    op.drop_index(op.f('ix_rosters_created_by'), table_name='rosters')
    op.create_index('ix_rosters_tenant_chapter_created', 'rosters', ['tenant_id', 'chapter_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_shifts_chore_id'), table_name='shifts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shifts_chore_id'), 'shifts', ['chore_id'], unique=False)
    op.drop_index('ix_rosters_tenant_chapter_created', table_name='rosters')
    op.create_index(op.f('ix_rosters_created_by'), 'rosters', ['created_by'], unique=False)
    op.drop_index('ix_occurrences_tenant_starts', table_name='occurrences')
    op.create_index(op.f('ix_occurrences_event_id'), 'occurrences', ['event_id'], unique=False)
    op.drop_index('ix_forms_tenant_mode_chapter_created', table_name='forms')
    op.create_index(op.f('ix_forms_created_by'), 'forms', ['created_by'], unique=False)
    op.drop_index('ix_events_tenant_chapter_created', table_name='events')
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.drop_index('ix_email_send_counts_tenant_day', table_name='email_send_counts')
    op.create_index(op.f('ix_email_send_counts_day'), 'email_send_counts', ['day'], unique=False)
    op.create_index(op.f('ix_email_dispatches_occurrence_id'), 'email_dispatches', ['occurrence_id'], unique=False)
    op.drop_index('ix_datepolls_tenant_chapter_created', table_name='datepolls')
    op.create_index(op.f('ix_datepolls_created_by'), 'datepolls', ['created_by'], unique=False)
    # ### end Alembic commands ###
