"""form question options become rows

Revision ID: 0ee637968420
Revises: 0a7d0d6080d3
Create Date: 2026-08-29 19:39:39.849264
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0ee637968420'
down_revision: str | None = '0a7d0d6080d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_question_options',
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('pole', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['form_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_question_options_question_id'), 'form_question_options', ['question_id'], unique=False)
    op.create_index('ix_form_question_options_question_ordinal', 'form_question_options', ['question_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_form_question_options_tenant_id'), 'form_question_options', ['tenant_id'], unique=False)
    op.create_table('form_response_choices',
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('option_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['form_question_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_form_response_choices_option', 'form_response_choices', ['option_id', 'response_id'], unique=False)
    op.create_index(op.f('ix_form_response_choices_option_id'), 'form_response_choices', ['option_id'], unique=False)
    op.create_index(op.f('ix_form_response_choices_response_id'), 'form_response_choices', ['response_id'], unique=False)
    op.create_index(op.f('ix_form_response_choices_tenant_id'), 'form_response_choices', ['tenant_id'], unique=False)
    op.create_table('form_question_options_archive',
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('pole', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_response_choices_archive',
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('option_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('form_questions', 'correct_choices')
    op.drop_column('form_questions', 'option_poles')
    op.drop_column('form_questions', 'options')
    op.drop_column('form_questions_archive', 'correct_choices')
    op.drop_column('form_questions_archive', 'option_poles')
    op.drop_column('form_questions_archive', 'options')
    op.drop_column('form_responses', 'answer_choices')
    op.drop_column('form_responses_archive', 'answer_choices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_responses_archive', sa.Column('answer_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('form_responses', sa.Column('answer_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ``server_default`` on the way back: the column is NOT NULL and the
    # table has rows, so it needs a value for them. Dropped again right
    # after, because the live model never carried one.
    op.add_column(
        'form_questions_archive',
        sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('form_questions_archive', 'options', server_default=None)
    op.add_column('form_questions_archive', sa.Column('option_poles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('form_questions_archive', sa.Column('correct_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column(
        'form_questions',
        sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('form_questions', 'options', server_default=None)
    op.add_column('form_questions', sa.Column('option_poles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('form_questions', sa.Column('correct_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('form_response_choices_archive')
    op.drop_table('form_question_options_archive')
    op.drop_index(op.f('ix_form_response_choices_tenant_id'), table_name='form_response_choices')
    op.drop_index(op.f('ix_form_response_choices_response_id'), table_name='form_response_choices')
    op.drop_index(op.f('ix_form_response_choices_option_id'), table_name='form_response_choices')
    op.drop_index('ix_form_response_choices_option', table_name='form_response_choices')
    op.drop_table('form_response_choices')
    op.drop_index(op.f('ix_form_question_options_tenant_id'), table_name='form_question_options')
    op.drop_index('ix_form_question_options_question_ordinal', table_name='form_question_options')
    op.drop_index(op.f('ix_form_question_options_question_id'), table_name='form_question_options')
    op.drop_table('form_question_options')
    # ### end Alembic commands ###
