"""link_recovered_at on all edit-token rows

Revision ID: 160bd9d63fe3
Revises: 6be2c0a71d3e
Create Date: 2026-07-05 09:47:44.087711
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '160bd9d63fe3'
down_revision: str | None = '6be2c0a71d3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepoll_submissions', sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('form_submissions', sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signups', sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('volunteers', sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'link_recovered_at')
    op.drop_column('signups', 'link_recovered_at')
    op.drop_column('form_submissions', 'link_recovered_at')
    op.drop_column('datepoll_submissions', 'link_recovered_at')
    # ### end Alembic commands ###
