"""user_chapters_multi

Revision ID: 17765cb75e74
Revises: e7e1d94c1c5d
Create Date: 2026-05-01 23:20:44.762608
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "17765cb75e74"
down_revision: str | None = "e7e1d94c1c5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chapters",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("chapter_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "chapter_id", name="pk_user_chapters"),
    )
    op.create_index(op.f("ix_user_chapters_chapter_id"), "user_chapters", ["chapter_id"], unique=False)
    op.create_index(op.f("ix_user_chapters_user_id"), "user_chapters", ["user_id"], unique=False)
    op.drop_index(op.f("ix_users_chapter_id"), table_name="users")
    op.drop_constraint(op.f("users_chapter_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "chapter_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("chapter_id", sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("users_chapter_id_fkey"), "users", "chapters", ["chapter_id"], ["id"], ondelete="SET NULL"
    )
    op.create_index(op.f("ix_users_chapter_id"), "users", ["chapter_id"], unique=False)
    op.drop_index(op.f("ix_user_chapters_user_id"), table_name="user_chapters")
    op.drop_index(op.f("ix_user_chapters_chapter_id"), table_name="user_chapters")
    op.drop_table("user_chapters")
    # ### end Alembic commands ###
