"""afdelingen scd2 + user/event afdeling_id

Revision ID: 190f36ee419b
Revises: 24ca586c0250
Create Date: 2026-04-26 14:13:26.533354
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '190f36ee419b'
down_revision: str | None = '24ca586c0250'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afdelingen',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('change_kind', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('afdelingen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afdelingen_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_afdelingen_valid_until'), ['valid_until'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afdeling_id', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_afdeling_id'), ['afdeling_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afdeling_id', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_afdeling_id'), ['afdeling_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_afdeling_id'))
        batch_op.drop_column('afdeling_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_afdeling_id'))
        batch_op.drop_column('afdeling_id')

    with op.batch_alter_table('afdelingen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_afdelingen_valid_until'))
        batch_op.drop_index(batch_op.f('ix_afdelingen_entity_id'))

    op.drop_table('afdelingen')
    # ### end Alembic commands ###
