"""member_survey_responses

Revision ID: 1dd56d59248c
Revises: 17765cb75e74
Create Date: 2026-05-04 19:26:56.143312
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1dd56d59248c'
down_revision: str | None = '17765cb75e74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_survey_responses',
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('q1_connected', sa.SmallInteger(), nullable=False),
    sa.Column('q2_clarity', sa.SmallInteger(), nullable=False),
    sa.Column('q3_likelihood', sa.SmallInteger(), nullable=False),
    sa.Column('q4_barriers', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('q4_other_text', sa.Text(), nullable=True),
    sa.Column('q5_helps', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_survey_responses')
    # ### end Alembic commands ###
