"""a name toggle on every product, and closing answers for changes

Revision ID: 22d316267bfb
Revises: c9cbd4c77e13
Create Date: 2026-08-27 22:39:48.184708
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '22d316267bfb'
down_revision: str | None = 'c9cbd4c77e13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepolls', sa.Column('name_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('datepolls', sa.Column('answers_editable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('events', sa.Column('name_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('answers_editable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('forms', sa.Column('answers_editable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('forms', sa.Column('name_required', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rosters', sa.Column('name_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosters', 'name_required')
    op.drop_column('forms', 'name_required')
    op.drop_column('forms', 'answers_editable')
    op.drop_column('events', 'answers_editable')
    op.drop_column('events', 'name_required')
    op.drop_column('datepolls', 'answers_editable')
    op.drop_column('datepolls', 'name_required')
    # ### end Alembic commands ###
