"""signup feedback email status + message id

Revision ID: 24ca586c0250
Revises: 04f3e8d1997d
Create Date: 2026-04-26 13:43:38.107218
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '24ca586c0250'
down_revision: str | None = '04f3e8d1997d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add columns with a server default so existing rows are valid; backfill
    # the status from the existing feedback_sent_at + encrypted_email
    # combination, then leave the server default in place for new rows.
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'feedback_email_status',
                sa.Text(),
                nullable=False,
                server_default='not_applicable',
            )
        )
        batch_op.add_column(sa.Column('feedback_message_id', sa.Text(), nullable=True))

    # Backfill: rows already processed by the worker → "sent"; rows still
    # holding ciphertext that haven't been processed → "pending".
    op.execute(
        "UPDATE signups SET feedback_email_status = 'sent' "
        "WHERE feedback_sent_at IS NOT NULL"
    )
    op.execute(
        "UPDATE signups SET feedback_email_status = 'pending' "
        "WHERE feedback_sent_at IS NULL AND encrypted_email IS NOT NULL"
    )

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signups_feedback_email_status'), ['feedback_email_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signups_feedback_message_id'), ['feedback_message_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signups_feedback_message_id'))
        batch_op.drop_index(batch_op.f('ix_signups_feedback_email_status'))
        batch_op.drop_column('feedback_message_id')
        batch_op.drop_column('feedback_email_status')

    # ### end Alembic commands ###
