"""archive twins for every table an archived item reaches

Twenty-three tables, one per live table that an archived event, form,
datepoll or roster can reach through a foreign key. Generated from the
live models rather than written out (backend/models/archive.py), so
a later migration that adds a column emits the ALTER for the pair.

No foreign keys and no indexes on the twins: an archived sign-up points
at an archived occurrence, and neither is in the table a key would
reference. Nothing reads them but a restore, which reads by id.

Revision ID: 2f2ca5e4d05a
Revises: f3483b5b6fa2
Create Date: 2026-08-29 09:17:31.892557
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '2f2ca5e4d05a'
down_revision: str | None = 'f3483b5b6fa2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores_archive',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('cycle_slots', sa.JSON(), nullable=False),
    sa.Column('people_per_shift', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compass_axes_archive',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('axis', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('low_name', sa.Text(), nullable=False),
    sa.Column('high_name', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datepoll_responses_archive',
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('datepoll_slot_id', sa.Text(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datepoll_slots_archive',
    sa.Column('datepoll_id', sa.Text(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datepoll_submissions_archive',
    sa.Column('datepoll_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('edit_token_hash', sa.Text(), nullable=True),
    sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datepolls_archive',
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('name_required', sa.Boolean(), nullable=False),
    sa.Column('answers_editable', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name_nl', sa.Text(), nullable=True),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_artist_instagram', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_send_counts_archive',
    sa.Column('occurrence_id', sa.Text(), nullable=False),
    sa.Column('channel', postgresql.ENUM('REMINDER', 'FEEDBACK', name='email_channel', create_type=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments_archive',
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('chore_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('volunteer_id', 'chore_id')
    )
    op.create_table('events_archive',
    sa.Column('topic_nl', sa.Text(), nullable=True),
    sa.Column('topic_en', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_options', sa.JSON(), nullable=False),
    sa.Column('source_enabled', sa.Boolean(), nullable=False),
    sa.Column('help_options', sa.JSON(), nullable=False),
    sa.Column('help_enabled', sa.Boolean(), nullable=False),
    sa.Column('feedback_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('name_required', sa.Boolean(), nullable=False),
    sa.Column('answers_editable', sa.Boolean(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('period_weeks', sa.Integer(), nullable=False),
    sa.Column('cycle_slots', sa.JSON(), nullable=False),
    sa.Column('span_weeks', sa.Integer(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name_nl', sa.Text(), nullable=True),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_artist_instagram', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_responses_archive',
    sa.Column('occurrence_id', sa.Text(), nullable=False),
    sa.Column('question_key', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_tokens_archive',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('occurrence_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_questions_archive',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('low_label', sa.Text(), nullable=True),
    sa.Column('high_label', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('correct_int', sa.Integer(), nullable=True),
    sa.Column('correct_text', sa.Text(), nullable=True),
    sa.Column('correct_choices', sa.JSON(), nullable=True),
    sa.Column('tolerance', sa.Integer(), nullable=True),
    sa.Column('pole', sa.Text(), nullable=True),
    sa.Column('option_poles', sa.JSON(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_responses_archive',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_choices', sa.JSON(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions_archive',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('edit_token_hash', sa.Text(), nullable=True),
    sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms_archive',
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('reveal_answers', sa.Boolean(), nullable=False),
    sa.Column('answers_editable', sa.Boolean(), nullable=False),
    sa.Column('name_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name_nl', sa.Text(), nullable=True),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_artist_instagram', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrences_archive',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations_archive',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('edit_token_hash', sa.Text(), nullable=True),
    sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosters_archive',
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('name_required', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('period_weeks', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('commit_horizon_days', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name_nl', sa.Text(), nullable=True),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_artist_instagram', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_events_archive',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('shift_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts_archive',
    sa.Column('chore_id', sa.Text(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signups_archive',
    sa.Column('registration_id', sa.Text(), nullable=False),
    sa.Column('occurrence_id', sa.Text(), nullable=False),
    sa.Column('source_choice', sa.Text(), nullable=True),
    sa.Column('help_choices', sa.JSON(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_availability_archive',
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers_archive',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('encrypted_email', sa.LargeBinary(), nullable=True),
    sa.Column('email_reminders', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('edit_token_hash', sa.Text(), nullable=True),
    sa.Column('link_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteers_archive')
    op.drop_table('volunteer_availability_archive')
    op.drop_table('signups_archive')
    op.drop_table('shifts_archive')
    op.drop_table('shift_events_archive')
    op.drop_table('rosters_archive')
    op.drop_table('registrations_archive')
    op.drop_table('occurrences_archive')
    op.drop_table('forms_archive')
    op.drop_table('form_submissions_archive')
    op.drop_table('form_responses_archive')
    op.drop_table('form_questions_archive')
    op.drop_table('feedback_tokens_archive')
    op.drop_table('feedback_responses_archive')
    op.drop_table('events_archive')
    op.drop_table('enrollments_archive')
    op.drop_table('email_send_counts_archive')
    op.drop_table('datepolls_archive')
    op.drop_table('datepoll_submissions_archive')
    op.drop_table('datepoll_slots_archive')
    op.drop_table('datepoll_responses_archive')
    op.drop_table('compass_axes_archive')
    op.drop_table('chores_archive')
    # ### end Alembic commands ###
