"""drop member_survey_responses

Revision ID: 37e4b9e81432
Revises: 61fa8fc82dd6
Create Date: 2026-06-06 20:54:23.815668
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '37e4b9e81432'
down_revision: str | None = '61fa8fc82dd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_survey_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_survey_responses',
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('q1_connected', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('q2_clarity', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('q3_likelihood', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('q4_barriers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('q4_other_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('q5_helps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('q6_anything_else', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('member_survey_responses_pkey'))
    )
    # ### end Alembic commands ###
