"""forms description + submissions table

Revision ID: 3d26c9d716c4
Revises: d415f0ffcf99
Create Date: 2026-06-13 22:06:13.066327
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3d26c9d716c4'
down_revision: str | None = 'd415f0ffcf99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submissions',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_foreign_key(
        'fk_form_responses_submission_id', 'form_responses', 'form_submissions',
        ['submission_id'], ['id'], ondelete='CASCADE',
    )
    op.add_column('forms', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'description')
    op.drop_constraint('fk_form_responses_submission_id', 'form_responses', type_='foreignkey')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    # ### end Alembic commands ###
