"""chores tables

Revision ID: 479117096b2f
Revises: 6264ee3dc1ee
Create Date: 2026-06-30 22:13:50.346219
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '479117096b2f'
down_revision: str | None = '6264ee3dc1ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosters',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('period_weeks', sa.Integer(), nullable=False),
    sa.Column('anchor_monday', sa.Date(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_artist_instagram', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rosters_archived_at'), 'rosters', ['archived_at'], unique=False)
    op.create_index('ix_rosters_archived_chapter', 'rosters', ['archived_at', 'chapter_id'], unique=False)
    op.create_index(op.f('ix_rosters_chapter_id'), 'rosters', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_rosters_created_by'), 'rosters', ['created_by'], unique=False)
    op.create_index(op.f('ix_rosters_slug'), 'rosters', ['slug'], unique=True)
    op.create_table('chores',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('cycle_slots', sa.JSON(), nullable=False),
    sa.Column('people_per_shift', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chores_roster_id'), 'chores', ['roster_id'], unique=False)
    op.create_table('volunteers',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('encrypted_email', sa.LargeBinary(), nullable=True),
    sa.Column('email_reminders', sa.Boolean(), nullable=False),
    sa.Column('edit_token_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteers_edit_token_hash'), 'volunteers', ['edit_token_hash'], unique=True)
    op.create_index(op.f('ix_volunteers_roster_id'), 'volunteers', ['roster_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('chore_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('volunteer_id', 'chore_id', name='pk_enrollments')
    )
    op.create_index(op.f('ix_enrollments_chore_id'), 'enrollments', ['chore_id'], unique=False)
    op.create_index(op.f('ix_enrollments_volunteer_id'), 'enrollments', ['volunteer_id'], unique=False)
    op.create_table('shifts',
    sa.Column('chore_id', sa.Text(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'done', 'open', 'missed')", name='ck_shifts_status'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'on_date', 'slot_index', name='uq_shifts_chore_date_slot')
    )
    op.create_index('ix_shifts_chore_date', 'shifts', ['chore_id', 'on_date'], unique=False)
    op.create_index(op.f('ix_shifts_chore_id'), 'shifts', ['chore_id'], unique=False)
    op.create_index(op.f('ix_shifts_volunteer_id'), 'shifts', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_volunteer_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_chore_id'), table_name='shifts')
    op.drop_index('ix_shifts_chore_date', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_enrollments_volunteer_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_chore_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_volunteers_roster_id'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_edit_token_hash'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_chores_roster_id'), table_name='chores')
    op.drop_table('chores')
    op.drop_index(op.f('ix_rosters_slug'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_created_by'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_chapter_id'), table_name='rosters')
    op.drop_index('ix_rosters_archived_chapter', table_name='rosters')
    op.drop_index(op.f('ix_rosters_archived_at'), table_name='rosters')
    op.drop_table('rosters')
    # ### end Alembic commands ###
