"""traffic counts

Revision ID: 570e0e090c01
Revises: fb1c34bb826c
Create Date: 2026-08-26 14:19:44.970262
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '570e0e090c01'
down_revision: str | None = 'fb1c34bb826c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_counts',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'surface', 'action', name='uq_traffic_day_surface_action')
    )
    op.create_index(op.f('ix_traffic_counts_day'), 'traffic_counts', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_counts_day'), table_name='traffic_counts')
    op.drop_table('traffic_counts')
    # ### end Alembic commands ###
