"""feedback questions, tokens, responses

Revision ID: 580c6db7929d
Revises: f6f3b8ee7105
Create Date: 2026-04-26 12:24:23.380938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '580c6db7929d'
down_revision: str | None = 'f6f3b8ee7105'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_questions',
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('feedback_responses',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_responses_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_responses_submission_id'), ['submission_id'], unique=False)

    op.create_table('feedback_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('signup_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_tokens_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_feedback_tokens_event_id'))

    op.drop_table('feedback_tokens')
    with op.batch_alter_table('feedback_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_responses_submission_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_responses_event_id'))

    op.drop_table('feedback_responses')
    op.drop_table('feedback_questions')
    # ### end Alembic commands ###
