"""volunteer_availability table

Revision ID: 58ca1def210f
Revises: 05b96c6951f1
Create Date: 2026-07-01 13:23:40.490448
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '58ca1def210f'
down_revision: str | None = '05b96c6951f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_availability',
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_availability_volunteer_id'), 'volunteer_availability', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_availability_volunteer_id'), table_name='volunteer_availability')
    op.drop_table('volunteer_availability')
    # ### end Alembic commands ###
