"""image fields on forms + datepolls

Revision ID: 58ef80aabcdb
Revises: 3d26c9d716c4
Create Date: 2026-06-13 22:57:20.390537
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '58ef80aabcdb'
down_revision: str | None = '3d26c9d716c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepolls', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('datepolls', sa.Column('image_artist_instagram', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('image_artist_instagram', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'image_artist_instagram')
    op.drop_column('forms', 'image_url')
    op.drop_column('datepolls', 'image_artist_instagram')
    op.drop_column('datepolls', 'image_url')
    # ### end Alembic commands ###
