"""bilingual title and description

Revision ID: 6023884ff187
Revises: 4f000956b809
Create Date: 2026-07-10 19:57:32.206654
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6023884ff187'
down_revision: str | None = '4f000956b809'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepolls', sa.Column('description_nl', sa.Text(), nullable=True))
    op.add_column('datepolls', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('datepolls', sa.Column('name_nl', sa.Text(), nullable=True))
    op.add_column('datepolls', sa.Column('name_en', sa.Text(), nullable=True))
    op.drop_column('datepolls', 'name')
    op.drop_column('datepolls', 'description')
    op.add_column('email_dispatches', sa.Column('locale', sa.Text(), server_default=sa.text("'nl'"), nullable=False))
    op.add_column('events', sa.Column('topic_nl', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('topic_en', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('name_nl', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('name_en', sa.Text(), nullable=True))
    op.drop_column('events', 'name')
    op.drop_column('events', 'topic')
    op.add_column('forms', sa.Column('description_nl', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('name_nl', sa.Text(), nullable=True))
    op.add_column('forms', sa.Column('name_en', sa.Text(), nullable=True))
    op.drop_column('forms', 'name')
    op.drop_column('forms', 'description')
    op.add_column('rosters', sa.Column('description_nl', sa.Text(), nullable=True))
    op.add_column('rosters', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('rosters', sa.Column('name_nl', sa.Text(), nullable=True))
    op.add_column('rosters', sa.Column('name_en', sa.Text(), nullable=True))
    op.drop_column('rosters', 'name')
    op.drop_column('rosters', 'description')
    op.add_column('volunteers', sa.Column('locale', sa.Text(), server_default=sa.text("'nl'"), nullable=False))
    # ### end Alembic commands ###

    # At least one language of the title must be set (the primary-language
    # one is required at the schema boundary). Raw-SQL check, so autogenerate
    # can't diff it — added and dropped by hand.
    for table in ("events", "datepolls", "forms", "rosters"):
        op.create_check_constraint(
            f"ck_{table}_name_present", table, "num_nonnulls(name_nl, name_en) >= 1"
        )


def downgrade() -> None:
    for table in ("events", "datepolls", "forms", "rosters"):
        op.drop_constraint(f"ck_{table}_name_present", table, type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'locale')
    op.add_column('rosters', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rosters', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('rosters', 'name_en')
    op.drop_column('rosters', 'name_nl')
    op.drop_column('rosters', 'description_en')
    op.drop_column('rosters', 'description_nl')
    op.add_column('forms', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('forms', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('forms', 'name_en')
    op.drop_column('forms', 'name_nl')
    op.drop_column('forms', 'description_en')
    op.drop_column('forms', 'description_nl')
    op.add_column('events', sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('events', 'name_en')
    op.drop_column('events', 'name_nl')
    op.drop_column('events', 'topic_en')
    op.drop_column('events', 'topic_nl')
    op.drop_column('email_dispatches', 'locale')
    op.add_column('datepolls', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('datepolls', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('datepolls', 'name_en')
    op.drop_column('datepolls', 'name_nl')
    op.drop_column('datepolls', 'description_en')
    op.drop_column('datepolls', 'description_nl')
    # ### end Alembic commands ###
