"""forms feature: form, form_questions, form_responses tables

Revision ID: 61fa8fc82dd6
Revises: d6f9cc45552a
Create Date: 2026-06-06 18:39:35.738947
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '61fa8fc82dd6'
down_revision: str | None = 'd6f9cc45552a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_archived_at'), 'forms', ['archived_at'], unique=False)
    op.create_index('ix_forms_archived_chapter', 'forms', ['archived_at', 'chapter_id'], unique=False)
    op.create_index(op.f('ix_forms_chapter_id'), 'forms', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_forms_created_by'), 'forms', ['created_by'], unique=False)
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    op.create_table('form_questions',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('low_label', sa.Text(), nullable=True),
    sa.Column('high_label', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_questions_form_id'), 'form_questions', ['form_id'], unique=False)
    op.create_table('form_responses',
    sa.Column('form_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('answer_int', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_choices', sa.JSON(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['form_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_form_id'), 'form_responses', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_responses_question_id'), 'form_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_form_responses_submission_id'), 'form_responses', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_submission_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_question_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_form_questions_form_id'), table_name='form_questions')
    op.drop_table('form_questions')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_created_by'), table_name='forms')
    op.drop_index(op.f('ix_forms_chapter_id'), table_name='forms')
    op.drop_index('ix_forms_archived_chapter', table_name='forms')
    op.drop_index(op.f('ix_forms_archived_at'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
