"""datepoll location + coordinates

Revision ID: 6264ee3dc1ee
Revises: bcfd44b30512
Create Date: 2026-06-14 09:10:54.825473
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6264ee3dc1ee'
down_revision: str | None = 'bcfd44b30512'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepolls', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('datepolls', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('datepolls', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datepolls', 'longitude')
    op.drop_column('datepolls', 'latitude')
    op.drop_column('datepolls', 'location')
    # ### end Alembic commands ###
