"""event options become rows

Revision ID: 9e905c01a135
Revises: 0ee637968420
Create Date: 2026-08-29 19:59:54.444109
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9e905c01a135'
down_revision: str | None = '0ee637968420'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_help_options',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_help_options_event_id'), 'event_help_options', ['event_id'], unique=False)
    op.create_index('ix_event_help_options_event_ordinal', 'event_help_options', ['event_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_event_help_options_tenant_id'), 'event_help_options', ['tenant_id'], unique=False)
    op.create_table('event_source_options',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_source_options_event_id'), 'event_source_options', ['event_id'], unique=False)
    op.create_index('ix_event_source_options_event_ordinal', 'event_source_options', ['event_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_event_source_options_tenant_id'), 'event_source_options', ['tenant_id'], unique=False)
    op.create_table('signup_help_choices',
    sa.Column('signup_id', sa.Text(), nullable=False),
    sa.Column('help_option_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['help_option_id'], ['event_help_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_help_choices_help_option_id'), 'signup_help_choices', ['help_option_id'], unique=False)
    op.create_index('ix_signup_help_choices_option', 'signup_help_choices', ['help_option_id', 'signup_id'], unique=False)
    op.create_index(op.f('ix_signup_help_choices_signup_id'), 'signup_help_choices', ['signup_id'], unique=False)
    op.create_index(op.f('ix_signup_help_choices_tenant_id'), 'signup_help_choices', ['tenant_id'], unique=False)
    op.create_table('event_help_options_archive',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_source_options_archive',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup_help_choices_archive',
    sa.Column('signup_id', sa.Text(), nullable=False),
    sa.Column('help_option_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('events', 'source_options')
    op.drop_column('events', 'help_options')
    op.drop_column('events_archive', 'source_options')
    op.drop_column('events_archive', 'help_options')
    op.add_column('signups', sa.Column('source_option_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_signups_source_option_id'), 'signups', ['source_option_id'], unique=False)
    op.create_foreign_key(
        'fk_signups_source_option_id',
        'signups',
        'event_source_options',
        ['source_option_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_column('signups', 'source_choice')
    op.drop_column('signups', 'help_choices')
    op.add_column('signups_archive', sa.Column('source_option_id', sa.Text(), nullable=True))
    op.drop_column('signups_archive', 'source_choice')
    op.drop_column('signups_archive', 'help_choices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'signups_archive',
        sa.Column('help_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('signups_archive', 'help_choices', server_default=None)
    op.add_column('signups_archive', sa.Column('source_choice', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('signups_archive', 'source_option_id')
    op.add_column(
        'signups',
        sa.Column('help_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('signups', 'help_choices', server_default=None)
    op.add_column('signups', sa.Column('source_choice', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_signups_source_option_id', 'signups', type_='foreignkey')
    op.drop_index(op.f('ix_signups_source_option_id'), table_name='signups')
    op.drop_column('signups', 'source_option_id')
    op.add_column(
        'events_archive',
        sa.Column('help_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('events_archive', 'help_options', server_default=None)
    op.add_column(
        'events_archive',
        sa.Column('source_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('events_archive', 'source_options', server_default=None)
    op.add_column(
        'events',
        sa.Column('help_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('events', 'help_options', server_default=None)
    op.add_column(
        'events',
        sa.Column('source_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                  nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('events', 'source_options', server_default=None)
    op.drop_table('signup_help_choices_archive')
    op.drop_table('event_source_options_archive')
    op.drop_table('event_help_options_archive')
    op.drop_index(op.f('ix_signup_help_choices_tenant_id'), table_name='signup_help_choices')
    op.drop_index(op.f('ix_signup_help_choices_signup_id'), table_name='signup_help_choices')
    op.drop_index('ix_signup_help_choices_option', table_name='signup_help_choices')
    op.drop_index(op.f('ix_signup_help_choices_help_option_id'), table_name='signup_help_choices')
    op.drop_table('signup_help_choices')
    op.drop_index(op.f('ix_event_source_options_tenant_id'), table_name='event_source_options')
    op.drop_index('ix_event_source_options_event_ordinal', table_name='event_source_options')
    op.drop_index(op.f('ix_event_source_options_event_id'), table_name='event_source_options')
    op.drop_table('event_source_options')
    op.drop_index(op.f('ix_event_help_options_tenant_id'), table_name='event_help_options')
    op.drop_index('ix_event_help_options_event_ordinal', table_name='event_help_options')
    op.drop_index(op.f('ix_event_help_options_event_id'), table_name='event_help_options')
    op.drop_table('event_help_options')
    # ### end Alembic commands ###
