"""tenant plan

Revision ID: c9cbd4c77e13
Revises: a3f21c9b7e40
Create Date: 2026-08-27 08:00:57.963924
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c9cbd4c77e13'
down_revision: str | None = 'a3f21c9b7e40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan', sa.Text(), server_default=sa.text("'free'"), nullable=False))
    op.create_check_constraint('ck_tenants_plan', 'tenants', "plan IN ('free', 'paid')")
    # The column default reads the kind (``models/tenants._plan_for_kind``);
    # rows that predate it get the same rule applied once.
    op.execute("UPDATE tenants SET plan = 'paid' WHERE kind = 'organisation'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tenants_plan', 'tenants', type_='check')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
