"""add city to afdelingen

Revision ID: d16b4999a699
Revises: a9f17bdef8cc
Create Date: 2026-04-27 11:37:43.412319
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd16b4999a699'
down_revision: str | None = 'a9f17bdef8cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('afdelingen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('city_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('afdelingen', schema=None) as batch_op:
        batch_op.drop_column('city_lon')
        batch_op.drop_column('city_lat')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
