"""datepolls feature

Revision ID: d415f0ffcf99
Revises: b044a128555a
Create Date: 2026-06-13 21:16:12.854356
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd415f0ffcf99'
down_revision: str | None = 'b044a128555a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datepolls',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datepolls_archived_at'), 'datepolls', ['archived_at'], unique=False)
    op.create_index('ix_datepolls_archived_chapter', 'datepolls', ['archived_at', 'chapter_id'], unique=False)
    op.create_index(op.f('ix_datepolls_chapter_id'), 'datepolls', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_datepolls_created_by'), 'datepolls', ['created_by'], unique=False)
    op.create_index(op.f('ix_datepolls_slug'), 'datepolls', ['slug'], unique=True)
    op.create_table('datepoll_dates',
    sa.Column('datepoll_id', sa.Text(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datepoll_id'], ['datepolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datepoll_id', 'on_date', name='uq_datepoll_dates_poll_date')
    )
    op.create_index(op.f('ix_datepoll_dates_datepoll_id'), 'datepoll_dates', ['datepoll_id'], unique=False)
    op.create_table('datepoll_submissions',
    sa.Column('datepoll_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datepoll_id'], ['datepolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datepoll_submissions_datepoll_id'), 'datepoll_submissions', ['datepoll_id'], unique=False)
    op.create_table('datepoll_responses',
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('datepoll_date_id', sa.Text(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("availability IN ('yes', 'no', 'maybe')", name='ck_datepoll_responses_availability'),
    sa.ForeignKeyConstraint(['datepoll_date_id'], ['datepoll_dates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['datepoll_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'datepoll_date_id', name='uq_datepoll_responses_submission_date')
    )
    op.create_index(op.f('ix_datepoll_responses_datepoll_date_id'), 'datepoll_responses', ['datepoll_date_id'], unique=False)
    op.create_index(op.f('ix_datepoll_responses_submission_id'), 'datepoll_responses', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datepoll_responses_submission_id'), table_name='datepoll_responses')
    op.drop_index(op.f('ix_datepoll_responses_datepoll_date_id'), table_name='datepoll_responses')
    op.drop_table('datepoll_responses')
    op.drop_index(op.f('ix_datepoll_submissions_datepoll_id'), table_name='datepoll_submissions')
    op.drop_table('datepoll_submissions')
    op.drop_index(op.f('ix_datepoll_dates_datepoll_id'), table_name='datepoll_dates')
    op.drop_table('datepoll_dates')
    op.drop_index(op.f('ix_datepolls_slug'), table_name='datepolls')
    op.drop_index(op.f('ix_datepolls_created_by'), table_name='datepolls')
    op.drop_index(op.f('ix_datepolls_chapter_id'), table_name='datepolls')
    op.drop_index('ix_datepolls_archived_chapter', table_name='datepolls')
    op.drop_index(op.f('ix_datepolls_archived_at'), table_name='datepolls')
    op.drop_table('datepolls')
    # ### end Alembic commands ###
