"""add locale to events

Revision ID: db9748610549
Revises: d16b4999a699
Create Date: 2026-04-27 13:15:12.681858
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'db9748610549'
down_revision: str | None = 'd16b4999a699'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add nullable, backfill 'nl' for existing rows, then tighten.
    with op.batch_alter_table("events") as batch_op:
        batch_op.add_column(sa.Column("locale", sa.Text(), nullable=True))
    op.execute("UPDATE events SET locale = 'nl' WHERE locale IS NULL")
    with op.batch_alter_table("events") as batch_op:
        batch_op.alter_column("locale", existing_type=sa.Text(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('locale')

    # ### end Alembic commands ###
