"""add archived_at to events

Revision ID: dd24331630ae
Revises: f4abfc678b5d
Create Date: 2026-04-26 12:53:49.067919
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'dd24331630ae'
down_revision: str | None = 'f4abfc678b5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_archived_at'), ['archived_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_archived_at'))
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
