"""member_survey_q6_anything_else

Revision ID: defb7b12f7c1
Revises: 1dd56d59248c
Create Date: 2026-05-05 13:43:06.964464
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'defb7b12f7c1'
down_revision: str | None = '1dd56d59248c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_survey_responses', sa.Column('q6_anything_else', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_survey_responses', 'q6_anything_else')
    # ### end Alembic commands ###
