"""registration_tokens

Revision ID: e7e1d94c1c5d
Revises: 029e6226f08b
Create Date: 2026-05-01 22:18:45.193642
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e7e1d94c1c5d"
down_revision: str | None = "029e6226f08b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_tokens",
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_registration_tokens_email"), "registration_tokens", ["email"], unique=False)
    op.create_index(op.f("ix_registration_tokens_token"), "registration_tokens", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registration_tokens_token"), table_name="registration_tokens")
    op.drop_index(op.f("ix_registration_tokens_email"), table_name="registration_tokens")
    op.drop_table("registration_tokens")
    # ### end Alembic commands ###
