"""shift_events

Revision ID: f0692bb588f6
Revises: 479117096b2f
Create Date: 2026-07-01 08:20:02.079240
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f0692bb588f6'
down_revision: str | None = '479117096b2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_events',
    sa.Column('roster_id', sa.Text(), nullable=False),
    sa.Column('volunteer_id', sa.Text(), nullable=False),
    sa.Column('shift_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('assigned', 'claimed', 'completed', 'deferred', 'missed')", name='ck_shift_events_kind'),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_events_roster_id'), 'shift_events', ['roster_id'], unique=False)
    op.create_index(op.f('ix_shift_events_volunteer_id'), 'shift_events', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_events_volunteer_id'), table_name='shift_events')
    op.drop_index(op.f('ix_shift_events_roster_id'), table_name='shift_events')
    op.drop_table('shift_events')
    # ### end Alembic commands ###
