"""the archive index: what was archived and when

Revision ID: f140412eb2b1
Revises: 2f2ca5e4d05a
Create Date: 2026-08-29 09:26:35.353435
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f140412eb2b1'
down_revision: str | None = '2f2ca5e4d05a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_index',
    sa.Column('root', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_index_entity_id'), 'archive_index', ['entity_id'], unique=False)
    op.create_index(op.f('ix_archive_index_tenant_id'), 'archive_index', ['tenant_id'], unique=False)
    op.create_index('ix_archive_index_tenant_root_archived', 'archive_index', ['tenant_id', 'root', 'archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_archive_index_tenant_root_archived', table_name='archive_index')
    op.drop_index(op.f('ix_archive_index_tenant_id'), table_name='archive_index')
    op.drop_index(op.f('ix_archive_index_entity_id'), table_name='archive_index')
    op.drop_table('archive_index')
    # ### end Alembic commands ###
