"""edit_token_hash on submissions

Revision ID: f382a112672b
Revises: 58ef80aabcdb
Create Date: 2026-06-14 00:10:19.163104
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f382a112672b'
down_revision: str | None = '58ef80aabcdb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepoll_submissions', sa.Column('edit_token_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_datepoll_submissions_edit_token_hash'), 'datepoll_submissions', ['edit_token_hash'], unique=True)
    op.add_column('form_submissions', sa.Column('edit_token_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_form_submissions_edit_token_hash'), 'form_submissions', ['edit_token_hash'], unique=True)
    op.add_column('signups', sa.Column('edit_token_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_signups_edit_token_hash'), 'signups', ['edit_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signups_edit_token_hash'), table_name='signups')
    op.drop_column('signups', 'edit_token_hash')
    op.drop_index(op.f('ix_form_submissions_edit_token_hash'), table_name='form_submissions')
    op.drop_column('form_submissions', 'edit_token_hash')
    op.drop_index(op.f('ix_datepoll_submissions_edit_token_hash'), table_name='datepoll_submissions')
    op.drop_column('datepoll_submissions', 'edit_token_hash')
    # ### end Alembic commands ###
