"""add email_verified_at to users

Revision ID: f4abfc678b5d
Revises: 580c6db7929d
Create Date: 2026-04-26 12:41:41.140281
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f4abfc678b5d'
down_revision: str | None = '580c6db7929d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
