"""add latitude/longitude to events

Revision ID: f6f3b8ee7105
Revises: cf80197e2fe9
Create Date: 2026-04-26 11:42:52.510162
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f6f3b8ee7105'
down_revision: str | None = 'cf80197e2fe9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
